// -- RIVALRY_MATCH_REACTION 穴埋め拡張 --
if (!RIVALRY_MATCH_REACTION.winnerLines.shy) RIVALRY_MATCH_REACTION.winnerLines.shy = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.shy.polite) RIVALRY_MATCH_REACTION.winnerLines.shy.polite = [];
RIVALRY_MATCH_REACTION.winnerLines.shy.polite.push('か、勝てました…でも…次も頑張らないと…');
if (!RIVALRY_MATCH_REACTION.winnerLines.emotional) RIVALRY_MATCH_REACTION.winnerLines.emotional = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.emotional.seductive) RIVALRY_MATCH_REACTION.winnerLines.emotional.seductive = [];
RIVALRY_MATCH_REACTION.winnerLines.emotional.seductive.push('勝ったわ…!でもまだ…まだ終わらないのよ…っ');
if (!RIVALRY_MATCH_REACTION.loserLines.shy) RIVALRY_MATCH_REACTION.loserLines.shy = {};
if (!RIVALRY_MATCH_REACTION.loserLines.shy.polite) RIVALRY_MATCH_REACTION.loserLines.shy.polite = [];
RIVALRY_MATCH_REACTION.loserLines.shy.polite.push('…負けてしまいました……悔しい…です…');
if (!RIVALRY_MATCH_REACTION.loserLines.bold) RIVALRY_MATCH_REACTION.loserLines.bold = {};
if (!RIVALRY_MATCH_REACTION.loserLines.bold.ojousama) RIVALRY_MATCH_REACTION.loserLines.bold.ojousama = [];
RIVALRY_MATCH_REACTION.loserLines.bold.ojousama.push('この負けは忘れませんわ。必ず借りは返しますの');
if (!RIVALRY_MATCH_REACTION.loserLines.emotional) RIVALRY_MATCH_REACTION.loserLines.emotional = {};
if (!RIVALRY_MATCH_REACTION.loserLines.emotional.seductive) RIVALRY_MATCH_REACTION.loserLines.emotional.seductive = [];
RIVALRY_MATCH_REACTION.loserLines.emotional.seductive.push('負けた…っ…でも、この気持ち…絶対に忘れないわ…');
if (!RIVALRY_MATCH_REACTION.winnerLines.normal) RIVALRY_MATCH_REACTION.winnerLines.normal = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.normal.polite) RIVALRY_MATCH_REACTION.winnerLines.normal.polite = [];
RIVALRY_MATCH_REACTION.winnerLines.normal.polite.push('今日のところは、わたしの勝ちです。次も…お待ちしています');
if (!RIVALRY_MATCH_REACTION.winnerLines.normal) RIVALRY_MATCH_REACTION.winnerLines.normal = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.normal.cool) RIVALRY_MATCH_REACTION.winnerLines.normal.cool = [];
RIVALRY_MATCH_REACTION.winnerLines.normal.cool.push('……今日は、わたしの勝ち');
if (!RIVALRY_MATCH_REACTION.winnerLines.normal) RIVALRY_MATCH_REACTION.winnerLines.normal = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.normal.ojousama) RIVALRY_MATCH_REACTION.winnerLines.normal.ojousama = [];
RIVALRY_MATCH_REACTION.winnerLines.normal.ojousama.push('本日はわたくしの勝利ですわ。次の機会もお待ちしてますの');
if (!RIVALRY_MATCH_REACTION.winnerLines.normal) RIVALRY_MATCH_REACTION.winnerLines.normal = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.normal.seductive) RIVALRY_MATCH_REACTION.winnerLines.normal.seductive = [];
RIVALRY_MATCH_REACTION.winnerLines.normal.seductive.push('今日はわたしの勝ちね。…次はどうなるかしら');
if (!RIVALRY_MATCH_REACTION.winnerLines.normal) RIVALRY_MATCH_REACTION.winnerLines.normal = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.normal.delinquent) RIVALRY_MATCH_REACTION.winnerLines.normal.delinquent = [];
RIVALRY_MATCH_REACTION.winnerLines.normal.delinquent.push('今日はこっちの勝ちだ。次もよろしくな');
if (!RIVALRY_MATCH_REACTION.winnerLines.normal) RIVALRY_MATCH_REACTION.winnerLines.normal = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.normal.composed) RIVALRY_MATCH_REACTION.winnerLines.normal.composed = [];
RIVALRY_MATCH_REACTION.winnerLines.normal.composed.push('…今日はわたしの勝ちだね。また次もよろしく');
if (!RIVALRY_MATCH_REACTION.winnerLines.bold) RIVALRY_MATCH_REACTION.winnerLines.bold = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.bold._default) RIVALRY_MATCH_REACTION.winnerLines.bold._default = [];
RIVALRY_MATCH_REACTION.winnerLines.bold._default.push('今のあなたじゃ、わたしは倒せない。鍛え直してきな');
if (!RIVALRY_MATCH_REACTION.winnerLines.bold) RIVALRY_MATCH_REACTION.winnerLines.bold = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.bold.polite) RIVALRY_MATCH_REACTION.winnerLines.bold.polite = [];
RIVALRY_MATCH_REACTION.winnerLines.bold.polite.push('今のあなたでは、わたしは倒せません。鍛え直してきてください');
if (!RIVALRY_MATCH_REACTION.winnerLines.bold) RIVALRY_MATCH_REACTION.winnerLines.bold = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.bold.ojousama) RIVALRY_MATCH_REACTION.winnerLines.bold.ojousama = [];
RIVALRY_MATCH_REACTION.winnerLines.bold.ojousama.push('今のあなたでは、わたくしを倒すなど百年早いですわ');
if (!RIVALRY_MATCH_REACTION.winnerLines.bold) RIVALRY_MATCH_REACTION.winnerLines.bold = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.bold.seductive) RIVALRY_MATCH_REACTION.winnerLines.bold.seductive = [];
RIVALRY_MATCH_REACTION.winnerLines.bold.seductive.push('今のあなたじゃ、わたしに届かないわ。…鍛え直してらっしゃい');
if (!RIVALRY_MATCH_REACTION.winnerLines.bold) RIVALRY_MATCH_REACTION.winnerLines.bold = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.bold.delinquent) RIVALRY_MATCH_REACTION.winnerLines.bold.delinquent = [];
RIVALRY_MATCH_REACTION.winnerLines.bold.delinquent.push('今のテメェじゃ、あたしには勝てねえ。出直してこい');
if (!RIVALRY_MATCH_REACTION.winnerLines.bold) RIVALRY_MATCH_REACTION.winnerLines.bold = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.bold.composed) RIVALRY_MATCH_REACTION.winnerLines.bold.composed = [];
RIVALRY_MATCH_REACTION.winnerLines.bold.composed.push('…今のあなたじゃ、わたしには届かない。また来なよ');
if (!RIVALRY_MATCH_REACTION.winnerLines.quiet) RIVALRY_MATCH_REACTION.winnerLines.quiet = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.quiet._default) RIVALRY_MATCH_REACTION.winnerLines.quiet._default = [];
RIVALRY_MATCH_REACTION.winnerLines.quiet._default.push('………(そっと去っていく)');
if (!RIVALRY_MATCH_REACTION.winnerLines.quiet) RIVALRY_MATCH_REACTION.winnerLines.quiet = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.quiet.polite) RIVALRY_MATCH_REACTION.winnerLines.quiet.polite = [];
RIVALRY_MATCH_REACTION.winnerLines.quiet.polite.push('………今日は、ここまでです');
if (!RIVALRY_MATCH_REACTION.winnerLines.quiet) RIVALRY_MATCH_REACTION.winnerLines.quiet = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.quiet.cool) RIVALRY_MATCH_REACTION.winnerLines.quiet.cool = [];
RIVALRY_MATCH_REACTION.winnerLines.quiet.cool.push('……終わり');
if (!RIVALRY_MATCH_REACTION.winnerLines.quiet) RIVALRY_MATCH_REACTION.winnerLines.quiet = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.quiet.seductive) RIVALRY_MATCH_REACTION.winnerLines.quiet.seductive = [];
RIVALRY_MATCH_REACTION.winnerLines.quiet.seductive.push('………今日のところは、ね');
if (!RIVALRY_MATCH_REACTION.winnerLines.shy) RIVALRY_MATCH_REACTION.winnerLines.shy = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.shy._default) RIVALRY_MATCH_REACTION.winnerLines.shy._default = [];
RIVALRY_MATCH_REACTION.winnerLines.shy._default.push('…あ、あの…ありがとう…ございました…');
if (!RIVALRY_MATCH_REACTION.winnerLines.shy) RIVALRY_MATCH_REACTION.winnerLines.shy = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.shy.polite) RIVALRY_MATCH_REACTION.winnerLines.shy.polite = [];
RIVALRY_MATCH_REACTION.winnerLines.shy.polite.push('…あ、あの…ありがとうございました…');
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing) RIVALRY_MATCH_REACTION.winnerLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing._default) RIVALRY_MATCH_REACTION.winnerLines.easygoing._default = [];
RIVALRY_MATCH_REACTION.winnerLines.easygoing._default.push('一勝一勝、積み重ねていくよ!次もよろしくね!');
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing) RIVALRY_MATCH_REACTION.winnerLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing.polite) RIVALRY_MATCH_REACTION.winnerLines.easygoing.polite = [];
RIVALRY_MATCH_REACTION.winnerLines.easygoing.polite.push('一勝ずつ、積み重ねていきます!次もよろしくお願いします!');
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing) RIVALRY_MATCH_REACTION.winnerLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing.ojousama) RIVALRY_MATCH_REACTION.winnerLines.easygoing.ojousama = [];
RIVALRY_MATCH_REACTION.winnerLines.easygoing.ojousama.push('一勝ずつ、積み重ねますわ!次もよろしくお願いしますの!');
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing) RIVALRY_MATCH_REACTION.winnerLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing.seductive) RIVALRY_MATCH_REACTION.winnerLines.easygoing.seductive = [];
RIVALRY_MATCH_REACTION.winnerLines.easygoing.seductive.push('一勝、積み重ねたわ。…次も楽しみにしてて');
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing) RIVALRY_MATCH_REACTION.winnerLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing.delinquent) RIVALRY_MATCH_REACTION.winnerLines.easygoing.delinquent = [];
RIVALRY_MATCH_REACTION.winnerLines.easygoing.delinquent.push('よし、一勝!次もガンガン行くぜ!');
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing) RIVALRY_MATCH_REACTION.winnerLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.easygoing.composed) RIVALRY_MATCH_REACTION.winnerLines.easygoing.composed = [];
RIVALRY_MATCH_REACTION.winnerLines.easygoing.composed.push('…一勝、積み重ねたよ。次もよろしくね');
if (!RIVALRY_MATCH_REACTION.winnerLines.earnest) RIVALRY_MATCH_REACTION.winnerLines.earnest = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.earnest._default) RIVALRY_MATCH_REACTION.winnerLines.earnest._default = [];
RIVALRY_MATCH_REACTION.winnerLines.earnest._default.push('勝利できました。でも油断はしません。次に備えます');
if (!RIVALRY_MATCH_REACTION.winnerLines.earnest) RIVALRY_MATCH_REACTION.winnerLines.earnest = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.earnest.polite) RIVALRY_MATCH_REACTION.winnerLines.earnest.polite = [];
RIVALRY_MATCH_REACTION.winnerLines.earnest.polite.push('勝たせていただきました。次に向けて、また鍛錬を積みます');
if (!RIVALRY_MATCH_REACTION.winnerLines.earnest) RIVALRY_MATCH_REACTION.winnerLines.earnest = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.earnest.ojousama) RIVALRY_MATCH_REACTION.winnerLines.earnest.ojousama = [];
RIVALRY_MATCH_REACTION.winnerLines.earnest.ojousama.push('勝たせていただきましたわ。次に向け、鍛錬を続けますの');
if (!RIVALRY_MATCH_REACTION.winnerLines.earnest) RIVALRY_MATCH_REACTION.winnerLines.earnest = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.earnest.seductive) RIVALRY_MATCH_REACTION.winnerLines.earnest.seductive = [];
RIVALRY_MATCH_REACTION.winnerLines.earnest.seductive.push('勝ったわ。でも油断はしない。…次に備えるの');
if (!RIVALRY_MATCH_REACTION.winnerLines.earnest) RIVALRY_MATCH_REACTION.winnerLines.earnest = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.earnest.composed) RIVALRY_MATCH_REACTION.winnerLines.earnest.composed = [];
RIVALRY_MATCH_REACTION.winnerLines.earnest.composed.push('…勝てました。次に向けて、また鍛錬します');
if (!RIVALRY_MATCH_REACTION.winnerLines.emotional) RIVALRY_MATCH_REACTION.winnerLines.emotional = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.emotional._default) RIVALRY_MATCH_REACTION.winnerLines.emotional._default = [];
RIVALRY_MATCH_REACTION.winnerLines.emotional._default.push('勝てた…っ!嬉しい…でも、次も…次も頑張らなきゃ…!');
if (!RIVALRY_MATCH_REACTION.winnerLines.emotional) RIVALRY_MATCH_REACTION.winnerLines.emotional = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.emotional.seductive) RIVALRY_MATCH_REACTION.winnerLines.emotional.seductive = [];
RIVALRY_MATCH_REACTION.winnerLines.emotional.seductive.push('勝ったわ…っ!この喜び…でも、次も負けないんだから…!');
if (!RIVALRY_MATCH_REACTION.winnerLines.emotional) RIVALRY_MATCH_REACTION.winnerLines.emotional = {};
if (!RIVALRY_MATCH_REACTION.winnerLines.emotional.composed) RIVALRY_MATCH_REACTION.winnerLines.emotional.composed = [];
RIVALRY_MATCH_REACTION.winnerLines.emotional.composed.push('…勝てた。…嬉しい…次も頑張る');
if (!RIVALRY_MATCH_REACTION.loserLines.normal) RIVALRY_MATCH_REACTION.loserLines.normal = {};
if (!RIVALRY_MATCH_REACTION.loserLines.normal.polite) RIVALRY_MATCH_REACTION.loserLines.normal.polite = [];
RIVALRY_MATCH_REACTION.loserLines.normal.polite.push('…この悔しさ、忘れません。次は必ず勝ちます');
if (!RIVALRY_MATCH_REACTION.loserLines.normal) RIVALRY_MATCH_REACTION.loserLines.normal = {};
if (!RIVALRY_MATCH_REACTION.loserLines.normal.cool) RIVALRY_MATCH_REACTION.loserLines.normal.cool = [];
RIVALRY_MATCH_REACTION.loserLines.normal.cool.push('……次は、こうはいかない');
if (!RIVALRY_MATCH_REACTION.loserLines.normal) RIVALRY_MATCH_REACTION.loserLines.normal = {};
if (!RIVALRY_MATCH_REACTION.loserLines.normal.ojousama) RIVALRY_MATCH_REACTION.loserLines.normal.ojousama = [];
RIVALRY_MATCH_REACTION.loserLines.normal.ojousama.push('この悔しさ、忘れませんわ。次は必ず');
if (!RIVALRY_MATCH_REACTION.loserLines.normal) RIVALRY_MATCH_REACTION.loserLines.normal = {};
if (!RIVALRY_MATCH_REACTION.loserLines.normal.seductive) RIVALRY_MATCH_REACTION.loserLines.normal.seductive = [];
RIVALRY_MATCH_REACTION.loserLines.normal.seductive.push('…この悔しさ、忘れないわ。次は必ずね');
if (!RIVALRY_MATCH_REACTION.loserLines.normal) RIVALRY_MATCH_REACTION.loserLines.normal = {};
if (!RIVALRY_MATCH_REACTION.loserLines.normal.delinquent) RIVALRY_MATCH_REACTION.loserLines.normal.delinquent = [];
RIVALRY_MATCH_REACTION.loserLines.normal.delinquent.push('くそっ…この借りは必ず返す。覚えとけよ');
if (!RIVALRY_MATCH_REACTION.loserLines.normal) RIVALRY_MATCH_REACTION.loserLines.normal = {};
if (!RIVALRY_MATCH_REACTION.loserLines.normal.composed) RIVALRY_MATCH_REACTION.loserLines.normal.composed = [];
RIVALRY_MATCH_REACTION.loserLines.normal.composed.push('…この悔しさ、忘れない。次は必ず');
if (!RIVALRY_MATCH_REACTION.loserLines.bold) RIVALRY_MATCH_REACTION.loserLines.bold = {};
if (!RIVALRY_MATCH_REACTION.loserLines.bold._default) RIVALRY_MATCH_REACTION.loserLines.bold._default = [];
RIVALRY_MATCH_REACTION.loserLines.bold._default.push('まだ本当の実力じゃない。次は絶対に勝ってみせる');
if (!RIVALRY_MATCH_REACTION.loserLines.bold) RIVALRY_MATCH_REACTION.loserLines.bold = {};
if (!RIVALRY_MATCH_REACTION.loserLines.bold.polite) RIVALRY_MATCH_REACTION.loserLines.bold.polite = [];
RIVALRY_MATCH_REACTION.loserLines.bold.polite.push('まだ本気ではありません。次は必ず、勝たせていただきます');
if (!RIVALRY_MATCH_REACTION.loserLines.bold) RIVALRY_MATCH_REACTION.loserLines.bold = {};
if (!RIVALRY_MATCH_REACTION.loserLines.bold.ojousama) RIVALRY_MATCH_REACTION.loserLines.bold.ojousama = [];
RIVALRY_MATCH_REACTION.loserLines.bold.ojousama.push('本気を出していないだけですわ。次は必ず勝ってみせますの');
if (!RIVALRY_MATCH_REACTION.loserLines.bold) RIVALRY_MATCH_REACTION.loserLines.bold = {};
if (!RIVALRY_MATCH_REACTION.loserLines.bold.seductive) RIVALRY_MATCH_REACTION.loserLines.bold.seductive = [];
RIVALRY_MATCH_REACTION.loserLines.bold.seductive.push('まだ本気じゃないのよ。次は必ず倒すわ');
if (!RIVALRY_MATCH_REACTION.loserLines.bold) RIVALRY_MATCH_REACTION.loserLines.bold = {};
if (!RIVALRY_MATCH_REACTION.loserLines.bold.delinquent) RIVALRY_MATCH_REACTION.loserLines.bold.delinquent = [];
RIVALRY_MATCH_REACTION.loserLines.bold.delinquent.push('まだ本気じゃねえ。次はぶっ潰す。覚えとけよ');
if (!RIVALRY_MATCH_REACTION.loserLines.bold) RIVALRY_MATCH_REACTION.loserLines.bold = {};
if (!RIVALRY_MATCH_REACTION.loserLines.bold.composed) RIVALRY_MATCH_REACTION.loserLines.bold.composed = [];
RIVALRY_MATCH_REACTION.loserLines.bold.composed.push('…まだ本気じゃない。次は勝つよ');
if (!RIVALRY_MATCH_REACTION.loserLines.quiet) RIVALRY_MATCH_REACTION.loserLines.quiet = {};
if (!RIVALRY_MATCH_REACTION.loserLines.quiet._default) RIVALRY_MATCH_REACTION.loserLines.quiet._default = [];
RIVALRY_MATCH_REACTION.loserLines.quiet._default.push('………(拳を握り、リングを見つめる)');
if (!RIVALRY_MATCH_REACTION.loserLines.quiet) RIVALRY_MATCH_REACTION.loserLines.quiet = {};
if (!RIVALRY_MATCH_REACTION.loserLines.quiet.polite) RIVALRY_MATCH_REACTION.loserLines.quiet.polite = [];
RIVALRY_MATCH_REACTION.loserLines.quiet.polite.push('………次は、負けません');
if (!RIVALRY_MATCH_REACTION.loserLines.quiet) RIVALRY_MATCH_REACTION.loserLines.quiet = {};
if (!RIVALRY_MATCH_REACTION.loserLines.quiet.cool) RIVALRY_MATCH_REACTION.loserLines.quiet.cool = [];
RIVALRY_MATCH_REACTION.loserLines.quiet.cool.push('……次だ');
if (!RIVALRY_MATCH_REACTION.loserLines.quiet) RIVALRY_MATCH_REACTION.loserLines.quiet = {};
if (!RIVALRY_MATCH_REACTION.loserLines.quiet.seductive) RIVALRY_MATCH_REACTION.loserLines.quiet.seductive = [];
RIVALRY_MATCH_REACTION.loserLines.quiet.seductive.push('………次は、逃がさないわよ');
if (!RIVALRY_MATCH_REACTION.loserLines.shy) RIVALRY_MATCH_REACTION.loserLines.shy = {};
if (!RIVALRY_MATCH_REACTION.loserLines.shy._default) RIVALRY_MATCH_REACTION.loserLines.shy._default = [];
RIVALRY_MATCH_REACTION.loserLines.shy._default.push('…ご、ごめんなさい……次は…頑張ります…');
if (!RIVALRY_MATCH_REACTION.loserLines.shy) RIVALRY_MATCH_REACTION.loserLines.shy = {};
if (!RIVALRY_MATCH_REACTION.loserLines.shy.polite) RIVALRY_MATCH_REACTION.loserLines.shy.polite = [];
RIVALRY_MATCH_REACTION.loserLines.shy.polite.push('…も、申し訳ございません……次は必ず…');
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing) RIVALRY_MATCH_REACTION.loserLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing._default) RIVALRY_MATCH_REACTION.loserLines.easygoing._default = [];
RIVALRY_MATCH_REACTION.loserLines.easygoing._default.push('あー、悔しい!でも、次こそは絶対やり返す!');
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing) RIVALRY_MATCH_REACTION.loserLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing.polite) RIVALRY_MATCH_REACTION.loserLines.easygoing.polite = [];
RIVALRY_MATCH_REACTION.loserLines.easygoing.polite.push('悔しいです!でも次こそは、必ずやり返します!');
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing) RIVALRY_MATCH_REACTION.loserLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing.ojousama) RIVALRY_MATCH_REACTION.loserLines.easygoing.ojousama = [];
RIVALRY_MATCH_REACTION.loserLines.easygoing.ojousama.push('悔しいですわ!でも次こそは、必ずやり返しますの!');
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing) RIVALRY_MATCH_REACTION.loserLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing.seductive) RIVALRY_MATCH_REACTION.loserLines.easygoing.seductive = [];
RIVALRY_MATCH_REACTION.loserLines.easygoing.seductive.push('悔しい…でも次こそは、必ずやり返すわ');
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing) RIVALRY_MATCH_REACTION.loserLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing.delinquent) RIVALRY_MATCH_REACTION.loserLines.easygoing.delinquent = [];
RIVALRY_MATCH_REACTION.loserLines.easygoing.delinquent.push('くっそー悔しい!次こそは絶対やり返すからな!');
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing) RIVALRY_MATCH_REACTION.loserLines.easygoing = {};
if (!RIVALRY_MATCH_REACTION.loserLines.easygoing.composed) RIVALRY_MATCH_REACTION.loserLines.easygoing.composed = [];
RIVALRY_MATCH_REACTION.loserLines.easygoing.composed.push('…悔しいね。でも次こそは、やり返すよ');
if (!RIVALRY_MATCH_REACTION.loserLines.earnest) RIVALRY_MATCH_REACTION.loserLines.earnest = {};
if (!RIVALRY_MATCH_REACTION.loserLines.earnest._default) RIVALRY_MATCH_REACTION.loserLines.earnest._default = [];
RIVALRY_MATCH_REACTION.loserLines.earnest._default.push('この敗北を糧にします。次は必ず、勝ってみせます');
if (!RIVALRY_MATCH_REACTION.loserLines.earnest) RIVALRY_MATCH_REACTION.loserLines.earnest = {};
if (!RIVALRY_MATCH_REACTION.loserLines.earnest.polite) RIVALRY_MATCH_REACTION.loserLines.earnest.polite = [];
RIVALRY_MATCH_REACTION.loserLines.earnest.polite.push('この敗北を糧にいたします。次は必ず、勝たせていただきます');
if (!RIVALRY_MATCH_REACTION.loserLines.earnest) RIVALRY_MATCH_REACTION.loserLines.earnest = {};
if (!RIVALRY_MATCH_REACTION.loserLines.earnest.ojousama) RIVALRY_MATCH_REACTION.loserLines.earnest.ojousama = [];
RIVALRY_MATCH_REACTION.loserLines.earnest.ojousama.push('この敗北を糧にいたしますわ。次は必ず勝ちますの');
if (!RIVALRY_MATCH_REACTION.loserLines.earnest) RIVALRY_MATCH_REACTION.loserLines.earnest = {};
if (!RIVALRY_MATCH_REACTION.loserLines.earnest.seductive) RIVALRY_MATCH_REACTION.loserLines.earnest.seductive = [];
RIVALRY_MATCH_REACTION.loserLines.earnest.seductive.push('この敗北を糧にするわ。次は必ず勝つの');
if (!RIVALRY_MATCH_REACTION.loserLines.earnest) RIVALRY_MATCH_REACTION.loserLines.earnest = {};
if (!RIVALRY_MATCH_REACTION.loserLines.earnest.composed) RIVALRY_MATCH_REACTION.loserLines.earnest.composed = [];
RIVALRY_MATCH_REACTION.loserLines.earnest.composed.push('…この敗北を糧にします。次は必ず');
if (!RIVALRY_MATCH_REACTION.loserLines.emotional) RIVALRY_MATCH_REACTION.loserLines.emotional = {};
if (!RIVALRY_MATCH_REACTION.loserLines.emotional._default) RIVALRY_MATCH_REACTION.loserLines.emotional._default = [];
RIVALRY_MATCH_REACTION.loserLines.emotional._default.push('うぅっ…悔しいっ…次は絶対に…絶対に勝つから…っ!');
if (!RIVALRY_MATCH_REACTION.loserLines.emotional) RIVALRY_MATCH_REACTION.loserLines.emotional = {};
if (!RIVALRY_MATCH_REACTION.loserLines.emotional.seductive) RIVALRY_MATCH_REACTION.loserLines.emotional.seductive = [];
RIVALRY_MATCH_REACTION.loserLines.emotional.seductive.push('悔しい…っ…次は絶対に…絶対に負けないわ…っ!');
if (!RIVALRY_MATCH_REACTION.loserLines.emotional) RIVALRY_MATCH_REACTION.loserLines.emotional = {};
if (!RIVALRY_MATCH_REACTION.loserLines.emotional.composed) RIVALRY_MATCH_REACTION.loserLines.emotional.composed = [];
RIVALRY_MATCH_REACTION.loserLines.emotional.composed.push('…っ…悔しい…次は、必ず');