// Portrait mapping: character id → filename key
// Usage: `image/face_${PORTRAIT[c.id]}.png`
const PORTRAIT = {
  1: 'abukuma_t', // 阿武隈塔子
  2: 'tomioka_k', // 富岡加奈子
  3: 'sawade_m', // 澤出みずき
  4: 'takatsu_k', // 高津小春
  5: 'fukamachi_m', // 深町真琴
  6: 'soezawa_t', // 副沢たまき
  7: 'takashina_m', // 高階まさみ
  8: 'hayashi_m', // 林真尋
  9: 'udagawa_r', // 宇田川里奈
  10: 'sato_y', // 佐藤ヨーコ
  11: 'tachibana_r', // 橘玲美
  12: 'ikoma_e', // 生駒エリカ
  13: 'domae_y', // 堂前ユキ
  14: 'kuroe_m', // 黒江舞
  15: 'kusunoki_n', // 楠木なぎさ
  16: 'okochi_s', // 大河内紗代子
  17: 'kawanobe_n', // 川野辺菜穂子
  18: 'dewa_t', // 出羽鷹子
  19: 'shijo_a', // 四条あずさ
  20: 'kishi_y', // 岸ゆみえ
  21: 'kinouchi_y', // 木ノ内幸音
  22: 'minoyama_m', // 美濃山まりな
  23: 'hayami_t', // 早見知子
  24: 'sonobe_r', // 園部梨花
  25: 'ishitoya_n', // 石戸谷なつき
  26: 'miyamori_n', // 宮守なつめ
  27: 'yaegashi_m', // 八重樫舞
  28: 'iwaya_m', // 岩屋みら
  29: 'aizawa_m', // 相沢未来
  30: 'matsukawa_a', // 松川杏樹
  31: 'hiramatsu_k', // 平松かなみ
  32: 'futasato_a', // 双里明日香
  33: 'umegaoka_m', // 梅ヶ丘みのり
  34: 'kitabatake_y', // 北畠吉乃
  35: 'uenohara_y', // 上野原弥生
  36: 'manabe_a', // 真鍋綾乃
  37: 'shirogane_r', // 白銀麗子
  38: 'shiba_a', // 芝彩音
  39: 'kamiya_s', // 神谷沙奈絵
  40: 'takanawa_m', // 高輪まみ
  41: 'negishi_a', // 根岸亞里亞
  42: 'hongo_m', // 本郷真理子
  43: 'kanazawa_f', // 金沢文
  44: 'fukuura_r', // 福浦理乃
  45: 'takatsuki_c', // 高槻千歳
  46: 'izawa_h', // 井沢遥
  47: 'saito_m', // 斎藤麻衣
  48: 'kikuchi_r', // 菊池璃子
  49: 'takahashi_ma', // 高橋まゆみ
  50: 'aida_m', // 相田萌
  51: 'mitsuhashi_f', // 三橋ふみえ
  52: 'nishikawa_c', // 西川ちあき
  53: 'komori_s', // 小森さなえ
  54: 'abe_m', // 阿部みのり
  55: 'okubo_m', // 大久保桃子
  56: 'katagiri_a', // 片桐ありさ
  57: 'asami_r', // 浅見里緒菜
  58: 'niwa_h', // 丹羽穂垂
  59: 'ikebe_m', // 池辺マリ
  60: 'banyubashi_h', // 馬入橋ほとり
  61: 'kannonzaki_s', // 観音崎せりか
  62: 'miyagase_c', // 宮ケ瀬千夏
  63: 'isehara_f', // 伊勢原文奈
  64: 'yumoto_h', // 湯本ほたる
  65: 'kurami_n', // 倉見菜々
  66: 'hasegawa_r', // 長谷川レオナ
  67: 'yanagishima_m', // 柳島みずほ
  68: 'oba_a', // 大庭愛菜
  69: 'hayakawa_m', // 早川モナ
  70: 'hamatake_m', // 浜竹美咲
  71: 'togane_s', // 東金沙織
  72: 'anazawa_h', // 穴澤ほのか
  73: 'omagoe_y', // 大馬越よし子
  74: 'fujimigaoka_h', // 富士見ヶ丘遥
  75: 'ebina_s', // 海老名栞
  76: 'kuribayashi_a', // 栗林あかり
  77: 'niimi_y', // 新見ゆり
  78: 'tsubakiyama_m', // 椿山みさき
  79: 'kudo_r', // 久堂梨々花
  80: 'takashima_s', // 高島さや
};