// ══════════════════════════════════════════════════════════════════════════════
//  src/lang-en.js — EN辞書 (Stage B P3b, 自動生成)
//
//  このファイルは test/i18n-build-dict.js が i18n/ui-ledger.json から生成する。
//  手動で編集しないこと。翻訳の追加・修正は i18n/ui-ledger.json の en 列を編集し、
//  node test/i18n-build-dict.js を再実行して再生成する。
//
//  生成元: i18n/ui-ledger.json (総キー3123件、訳文あり1573件)
//  D-B2(i18n-stage-b-p3b-design-v0.1.md): 辞書に無いキーは原文のままfail-openで表示される。
//  よってこのファイルは訳文を部分的に持つ状態のまま安全にコミットできる。
// ══════════════════════════════════════════════════════════════════════════════
(function () {
  'use strict';
  if (typeof WM_I18N === 'undefined' || !WM_I18N.addDict) return;
  WM_I18N.addDict(
  {
    "\r\n        ← 戻る\r\n      ": "\r\n        ← Back\r\n      ",
    "\r\n      ゲーム開始\r\n    ": "\r\n      Start Game\r\n    ",
    "\r\n      旗揚げする\r\n    ": "\r\n      Found the Promotion\r\n    ",
    " (成功率80%)": " (80% success rate)",
    " (確定成功)": " (guaranteed success)",
    " (評価 {n})": " (rating {n})",
    " / {n}週離脱": " / out {n} weeks",
    " / ライバル {n}件": " / {n} rivals",
    " / 接戦+{n}": " / close match +{n}",
    " / 目標3,000万": " / target ¥30,000k",
    " ─ 継続中": " ─ ongoing",
    "(4週ごとに費用と決裁枠⚡{n}を再消費)": "(costs money and ⚡{n} approvals again every 4 weeks)",
    "({n}週)": "({n} weeks)",
    "+12（両方向）": "+12 (both directions)",
    "+1〜2": "+1 to 2",
    "+{n}（継承）": "+{n} (inherited)",
    "+{v}万": "+¥{v}0k",
    "+保持": "+holding",
    "+微増": "+slight rise",
    "--- なし ---": "--- none ---",
    "-0.02（下限0.85）": "-0.02 (floor 0.85)",
    "-1（炎上）": "-1 (backlash)",
    "-40（両方向）": "-40 (both directions)",
    "-{v}万": "-¥{v}0k",
    "/ 2 選択中": "/ 2 selected",
    "/ 全体{n}試合目": "/ match {n} overall",
    "/期": "/season",
    "/週": "/week",
    "0 リセット": "0 reset",
    "02 — Roster": "02 — Roster",
    "03 — 団体詳細": "03 — Promotion Detail",
    "04 — History": "04 — History",
    "1.6秒で自動的に進みます(タップで即スキップ)": "Advances automatically after 1.6 seconds (tap to skip)",
    "12週": "12 weeks",
    "12週 CD": "12-week cooldown",
    "15分1本勝負": "15-Minute One Fall",
    "1人目": "Wrestler 1",
    "1回戦": "Round 1",
    "1試合結果": "Match Result",
    "20代半ばにさしかかる頃から、リングに上がり続けた分だけ毎年少しずつ蓄積します。そこに上乗せされるのが——": "From about the middle of her twenties, every year she keeps stepping into the ring adds a little more wear. And on top of that comes—",
    "20分1本勝負": "20-Minute One Fall",
    "2人目": "Wrestler 2",
    "2名間 rivalry": "rivalry between the two",
    "2名間の因縁 <strong>{n}</strong> / 100 — 火種は熟している": "Grudge between the two <strong>{n}</strong> / 100 — the spark is ready to catch",
    "2派閥メンバーの離脱リスク": "Risk of members leaving both factions",
    "3-4位": "3rd–4th",
    "30分1本勝負": "30-Minute One Fall",
    "3人制シングル3連戦": "3-on-3, three straight singles",
    "3人制・シングル3連戦": "3-on-3 · Three Straight Singles",
    "3位": "3rd",
    "3軸の合算:<br>・コア戦力 {force}　TOP8加重OVR×1.2 ＋ 加重人気×0.6<br>・層の厚み {depth}　主力層 {depthCore}/20 ＋ 控え層 {depthReserve}/10<br>・看板スター {marquee}　TOP3人気の突出加重×0.45<br>怪我人・引退・レンタル選手は除外。": "Sum of three axes:<br>• Core strength {force} — TOP8 weighted OVR×1.2 + weighted popularity×0.6<br>• Depth {depth} — Front line {depthCore}/20 + Reserves {depthReserve}/10<br>• Marquee star {marquee} — TOP3 popularity peak weighting×0.45<br>Injured, retired and loan wrestlers are excluded.",
    "4〜8位5人の平均OVRが80で100点 (8人未満は不足枠OVR=0)": "An average OVR of 80 across ranks 4–8 scores 100 (missing slots count as OVR 0)",
    "4〜8番手の主力層と、9〜12番手の控え層を別々に評価。基準は業界の主力水準に連動します。怪我人・レンタルは含みません。": "Ranks 4–8 (the front line) and ranks 9–12 (the reserves) are scored separately. The bar tracks the industry's front-line standard. Injured and loan wrestlers are not counted.",
    "4位": "4th",
    "4年に一度、業界の頂を決める舞台": "Once every four years, the stage that decides the top of the industry",
    "4年に一度の全国女子プロレス最強王者決定戦。<br>特別招待2名に続き、団体枠 {n}名を選出してください。": "The national tournament held every four years to crown the strongest woman in wrestling.<br>After the two special invitations, choose {n} wrestlers for your promotion's slots.",
    "4年に一度の大舞台まで、あと6週": "Six weeks until the stage that comes once every four years",
    "4年に一度の祭典": "A festival held once every four years",
    "4年周期": "Every four years",
    "<b>{n}</b>シーズン": "<b>{n}</b> seasons",
    "<b>{n}</b>度戴冠": "<b>{n}</b>-time champion",
    "<b>{n}</b>度防衛": "<b>{n}</b> defenses",
    "<strong style=\"color:var(--gold)\">⚡ 決裁枠</strong><br>\r\n社長室の書類を決裁するのに使う。<br>\r\n<span style=\"color:var(--text-sub)\"><strong style=\"color:var(--text-main)\">4週ごとに2</strong>回復（上限{dpMax}）</span>": "<strong style=\"color:var(--gold)\">⚡ Approvals</strong><br>\r\nSpent to approve the documents on your desk.<br>\r\n<span style=\"color:var(--text-sub)\"><strong style=\"color:var(--text-main)\">+2 every 4 weeks</strong> (cap {dpMax})</span>",
    "<strong style=\"color:var(--gold)\">⚡ 決裁枠</strong><br>\r\n社長室の書類を決裁するのに使う。<br>\r\n<span style=\"color:var(--text-sub)\"><strong style=\"color:var(--text-main)\">4週ごとに2</strong>回復（上限{dpMax}）</span><br><br><span style=\"color:var(--text-sub);font-size:11px\">いまは満タン。<strong style=\"color:var(--text-main)\">次の回復は捨てられる</strong></span>": "<strong style=\"color:var(--gold)\">⚡ Approvals</strong><br>\r\nSpent to approve the documents on your desk.<br>\r\n<span style=\"color:var(--text-sub)\"><strong style=\"color:var(--text-main)\">+2 every 4 weeks</strong> (cap {dpMax})</span><br><br><span style=\"color:var(--text-sub);font-size:11px\">Full right now. <strong style=\"color:var(--text-main)\">The next refill will go to waste</strong></span>",
    "<strong style=\"color:var(--gold)\">⚡追込練習</strong><br>成長が大きく伸びる代わりに体調の消耗が激しく、怪我のリスクも上がります。<br><br>体調50以上・最大2週連続まで。": "<strong style=\"color:var(--gold)\">⚡ Hard Training</strong><br>Growth jumps, but condition drains fast and the injury risk climbs.<br><br>Requires condition 50 or above, two consecutive weeks at most.",
    "<strong style=\"color:var(--gold)\">おまかせ編成</strong><br>・🔥おすすめ — 因縁・鮮度・話題性を考慮した最適カード<br>・💪OVR順 — 実力上位同士をマッチング<br>・🎤集客力順 — 集客力の高い選手をメインに": "<strong style=\"color:var(--gold)\">Auto Booking</strong><br>• 🔥 Recommended — the best card, weighing grudges, freshness and buzz<br>• 💪 By OVR — the strongest against the strongest<br>• 🎤 By Draw — puts your biggest draws on top",
    "<strong style=\"color:var(--gold)\">育成方針</strong><br>・<strong>バランス</strong> — 興行週はプロモ、練習週は練習。迷ったらこれ<br>・<strong>練習優先</strong> — ステータス成長に集中<br>・<strong>プロモ優先</strong> — 人気を上げる(上限あり)<br>・<strong>休養重視</strong> — 確実に休ませる<br><br>どの方針でも、体調60未満になると自動で休養します。": "<strong style=\"color:var(--gold)\">Training Policy</strong><br>• <strong>Balanced</strong> — promo on show weeks, training on practice weeks. The safe default<br>• <strong>Training First</strong> — concentrates on stat growth<br>• <strong>Promo First</strong> — raises popularity (up to a ceiling)<br>• <strong>Rest First</strong> — guarantees time off<br><br>Under any policy, a wrestler rests automatically once her condition falls below 60.",
    "<strong style=\"color:var(--gold)\">🏛️ 地域振興助成金</strong><br>\r\n現在の支給額: <strong style=\"color:#2ecc71\">+{subsidyAmt}万/週</strong>（自動）<br>\r\n<span style=\"color:#aaa\">人気があと<strong style=\"color:#fff\">{remaining}pt</strong>上がると打ち切り</span><br><br>\r\n<span style=\"color:#aaa;font-size:11px\">打ち切り後はスポンサー収入が<br>10万 → <strong style=\"color:#fff\">30万/週</strong>に増えます</span>": "<strong style=\"color:var(--gold)\">🏛️ Regional Development Grant</strong><br>\r\nCurrent payment: <strong style=\"color:#2ecc71\">+¥{subsidyAmt}0k/week</strong> (automatic)<br>\r\n<span style=\"color:#aaa\">Ends once popularity rises another <strong style=\"color:#fff\">{remaining}pt</strong></span><br><br>\r\n<span style=\"color:#aaa;font-size:11px\">After it ends, sponsor income rises from<br>¥100k to <strong style=\"color:#fff\">¥300k/week</strong></span>",
    "<strong style=\"color:var(--gold)\">🤖 おまかせ</strong><br>体調80未満の選手を休養にし、体調80以上で休養方針の選手をバランスに戻します。それ以外の方針は維持されます。": "<strong style=\"color:var(--gold)\">🤖 Auto</strong><br>Puts anyone below condition 80 on rest, and brings anyone at 80 or above back from rest to balanced. Every other policy is left alone.",
    "<strong>{a}</strong> × <strong>{b}</strong> — 枠は自由。カード編成のどこに置くかは社長次第": "<strong>{a}</strong> × <strong>{b}</strong> — the slot is open. Where it lands on the card is up to you",
    "<strong>{name}</strong> をメインで使うと約束している — 組むかどうかは社長次第": "You promised <strong>{name}</strong> the main event — whether you book it is up to you",
    "<strong>{winner}</strong>が<strong>{finish}</strong>で勝利": "<strong>{winner}</strong> wins by <strong>{finish}</strong>",
    "<strong>{winner}</strong>が勝利": "<strong>{winner}</strong> wins",
    "A1位": "A Block winner",
    "Aランク挑戦者": "A-rank challenger",
    "A級": "Class A",
    "A級コーチの雇用には4枠目の開放が必要です": "Hiring a Class A coach requires opening a fourth slot",
    "B1位": "B Block winner",
    "BGMのみ ON/OFF（効果音・ジングルは残る）": "Music only, on or off (sound effects and jingles stay)",
    "BOOTH で製品版をチェックしてください。": "Check out the full version on BOOTH.",
    "BOOTH で購入": "Buy on BOOTH",
    "Bランク": "B rank",
    "B級": "Class B",
    "C級": "Class C",
    "F08 CD": "F08 cooldown",
    "Final Standing — 最終順位": "Final Standing",
    "JSONファイルを選択するとすぐにロードされます": "Selecting a JSON file loads it straight away",
    "JTへ進む": "Go to the JT",
    "JT優勝": "JT winner",
    "JT優勝 / 新人王": "JT winner / Rookie of the Year",
    "JT優勝{n}回": "JT winner ×{n}",
    "JT優勝・新人王": "JT winner · Rookie of the Year",
    "L1 — 先鋒・中堅・大将": "L1 — Lead-off · Middle · Captain",
    "L1 — 決勝の先鋒・中堅・大将": "L1 — Final: Lead-off · Middle · Captain",
    "MNは試合経験で成長します": "MN grows through match experience",
    "MVP2 ／ 新人王1.5 ／ ベストマッチ1 ／ メディア功労賞1.5": "MVP 2 / Rookie of the Year 1.5 / Best Match 1 / Media Merit Award 1.5",
    "MVPレース": "MVP Race",
    "MVPレース詳細 ▶": "MVP Race Detail ▶",
    "OVR — 基準値": "OVR — Base Values",
    "OVR<strong>{ovr}</strong>": "OVR <strong>{ovr}</strong>",
    "OVR<strong>{ovr}</strong> / 人気<strong>{pop}</strong>": "OVR <strong>{ovr}</strong> / Pop <strong>{pop}</strong>",
    "OVR<strong>{ovr}</strong> / 人気<strong>{pop}</strong> / 年齢<strong>{age}</strong>": "OVR <strong>{ovr}</strong> / Pop <strong>{pop}</strong> / Age <strong>{age}</strong>",
    "OVR<strong>{ovr}</strong> 人気<strong>{pop}</strong>": "OVR <strong>{ovr}</strong> Pop <strong>{pop}</strong>",
    "OVR上位同士をマッチング": "Matches the highest OVR against each other",
    "OVR幅 {a}〜{b} / 出場順は開戦時に公開": "OVR range {a}–{b} / running order revealed at bell time",
    "OVR幅 {a}〜{b} / 最終出場順は開戦時に公開": "OVR range {a}–{b} / final running order revealed at bell time",
    "OVR昇順で、大将に最強選手を置くのがおまかせ編成です。": "Auto booking sorts by OVR and puts your strongest wrestler last, as captain.",
    "PPV カードを表示": "Show the PPV Card",
    "PPV 第{n}試合": "PPV Match {n}",
    "PPV優勝": "PPV winner",
    "PPV優勝{n}回": "PPV winner ×{n}",
    "PPV対決<strong>あり</strong>": "PPV meeting: <strong>yes</strong>",
    "PPV最終戦勝者": "Winner of the final PPV match",
    "PPV経験<strong>あり</strong>": "PPV experience: <strong>yes</strong>",
    "Profile — 紹介": "Profile",
    "R{n}で離脱": "Out in R{n}",
    "Sランク王者": "S-rank champion",
    "S級": "Class S",
    "TOP3平均OVRが100で100点 (上限100)": "An average OVR of 100 across your top 3 scores 100 (capped at 100)",
    "TOP5実力": "Top 5 Strength",
    "TOP5平均人気が80で100点 (上限100)": "An average popularity of 80 across your top 5 scores 100 (capped at 100)",
    "Traits — 特性": "Traits",
    "U-20ジュニアトーナメント進行中": "U-20 Junior Tournament in progress",
    "YEAR {season} ・ WEEK {week} ・ 第{n}試合 / 全{total}試合": "YEAR {season} · WEEK {week} · Match {n} of {total}",
    "dictatorTag 付与": "grant dictatorTag",
    "pt で頂点": "pts to the summit",
    "{age}年前 ({season}年目)": "{age} years ago (Year {season})",
    "{age}歳": "Age {age}",
    "{age}歳 / {h}cm": "Age {age} / {h}cm",
    "{age}歳・{style}": "Age {age} · {style}",
    "{alloc}。編成期間は来週(第{w}週)です。": "{alloc}. Team entry runs next week (Week {w}).",
    "{a} <strong>{wa}</strong>勝 / {b} <strong>{wb}</strong>勝": "{a} <strong>{wa}</strong> wins / {b} <strong>{wb}</strong> wins",
    "{a} vs {b} は、次の通常興行のメインイベントで行われます。": "{a} vs {b} will headline your next regular show.",
    "{a} → {b} bond": "{a} → {b} bond",
    "{a} → {b} 因縁": "{a} → {b} grudge",
    "{a} → {b} 対立度": "{a} → {b} hostility",
    "{a} ⇄ {b} bond": "{a} ⇄ {b} bond",
    "{a} ⇄ {b} 因縁": "{a} ⇄ {b} grudge",
    "{a} ⇄ {b} 対立度": "{a} ⇄ {b} hostility",
    "{a} リーダー vs {b} リーダー": "{a} leader vs {b} leader",
    "{a}/{b}チーム編成済み。未編成枠は締切時に、未選出選手のOVR上位からおまかせ編成されます。": "{a}/{b} teams entered. Any empty slots are filled at the deadline, taking the highest-OVR wrestlers still unselected.",
    "{a}/{b}名": "{a}/{b}",
    "{a}<strong>{wa}</strong>勝 / {b}<strong>{wb}</strong>勝": "{a} <strong>{wa}</strong> wins / {b} <strong>{wb}</strong> wins",
    "{a}と{b}——{sub}": "{a} and {b} — {sub}",
    "{a}と{b}――その夜、両派閥のリーダーが直接拳を交える。": "{a} and {b} — that night, the two faction leaders trade punches themselves.",
    "{a}と{b}、両リーダーの直接対決を次興行のメインに据えると決めた。": "You decided to put {a} and {b}, the two leaders, in the main event of the next show.",
    "{a}と{b}。{n}戦のぶつかり合い。": "{a} and {b}. A rivalry {n} matches deep.",
    "{a}と{b}のリーダー対決を、今週のメインイベントとして公式戦に組みました": "You booked the leaders' showdown between {a} and {b} as this week's main event, on the official card",
    "{a}と{b}の争いをリングに持ち込む方針を取った。観客はこの火種を見逃さないだろう。": "You chose to carry the quarrel between {a} and {b} into the ring. The crowd will not miss a spark like this.",
    "{a}と{b}の対立は、社長の仲裁によって沈静化した。まだ完全な和解ではないが、互いに矛を収める段階に入った。": "Your mediation cooled the conflict between {a} and {b}. It is not a full reconciliation, but both sides have lowered their weapons.",
    "{a}と{b}の火種は、ついにリングで燃え上がる。": "The spark between {a} and {b} finally catches fire in the ring.",
    "{a}と{b}は決着つかず。": "{a} and {b} settle nothing.",
    "{a}と{b}は適度な距離を保った。関係は穏やかなまま。": "{a} and {b} kept a sensible distance. Things stayed calm between them.",
    "{a}は後押しを喜ぶ ／ {b}はえこひいきと感じる": "{a} welcomes the push / {b} reads it as favoritism",
    "{block}ブロック": "Block {block}",
    "{block}ブロック ": "Block {block} ",
    "{block}ブロック 第{n}試合": "Block {block} Match {n}",
    "{block}ブロック{n}位": "Block {block} #{n}",
    "{cat}収入": "{cat} revenue",
    "{corner}選手を選択": "Choose the {corner} wrestler",
    "{cost}万×人数": "¥{cost}0k × head count",
    "{count}を乗せたバスが、{venue}へ向かっています。": "The bus carrying {count} is on its way to {venue}.",
    "{count}を乗せた車が、他団体の会場へ向かっています。": "The car carrying {count} is on its way to another promotion's venue.",
    "{date} 完了": "{date} complete",
    "{date} ｜ 資金{funds}万 ｜ {saved}": "{date} | Funds ¥{funds}0k | {saved}",
    "{date} ｜ 資金{funds}万 ｜ 人気{pop} ｜ 所属{n}名": "{date} | Funds ¥{funds}0k | Popularity {pop} | Roster {n}",
    "{delta}(解消)": "{delta} (cleared)",
    "{d}（両方向）": "{d} (both directions)",
    "{faction}内の序列を懸けた一戦に決着がついた。": "The match for rank inside {faction} has been settled.",
    "{funds}万": "¥{funds}0k",
    "{grade}級コーチ": "Class {grade} coach",
    "{g}級のコーチ": "a Class {g} coach",
    "{h}cm ｜ {age}歳 ｜ {tenure}年目": "{h}cm | Age {age} | Year {tenure}",
    "{label} 第{a}週、年間第{b}週": "{label} Week {a}, Week {b} of the year",
    "{label} 開催週": "{label} show week",
    "{label}(第{n}回)": "{label} (#{n})",
    "{label}に強いコーチ": "A coach strong in {label}",
    "{label}の対立": "{label} conflict",
    "{label}の段階": "the {label} stage",
    "{leader}ではなく別の幹部を重用した。{faction}の中に、新たな対立軸がくすぶっている。": "You leaned on another lieutenant instead of {leader}. A new fault line is smoldering inside {faction}.",
    "{leader}と給与改定を約束した。{faction}のメンバーへ+10%、来週から実支給に反映される。": "You promised {leader} a pay revision. Members of {faction} get +10%, effective in next week's payroll.",
    "{leader}に直接は触れず、コーチを介して練習量を整えた。": "Rather than approach {leader} directly, you had the coaches adjust the training load.",
    "{leader}に直接話をつけた。{target}は救われた表情を見せた。": "You settled it with {leader} face to face. {target} looked relieved.",
    "{leader}に練習出席を求めた。{faction}内には緊張が走った。": "You told {leader} to show up for practice. A tension ran through {faction}.",
    "{leader}の声を受け止め、向こう{n}興行のメインカードに{faction}を推す方針を伝えた。": "You heard {leader} out and told her {faction} would be pushed at the top of the card for the next {n} shows.",
    "{leader}の権威を認めた。{faction}の外にいる者たちは、一歩引いて見ている。": "You acknowledged {leader}'s authority. The wrestlers outside {faction} are watching from a step back.",
    "{leader}の要求そのものには応じず、{faction}のメンバー一人一人に目を配った。": "You did not grant {leader}'s demand itself, but you looked in on every member of {faction} one by one.",
    "{leader}の要求は受け流した。{faction}の中に、薄い不満が漂う。": "You let {leader}'s demand pass. A thin discontent hangs inside {faction}.",
    "{leader}の追い込みを止めた。{faction}は一息ついた。": "You called off {leader}'s hard drilling. {faction} caught its breath.",
    "{leader}の追い込み練習を黙認した。": "You let {leader}'s hard drilling go on without comment.",
    "{leader}本人ではなく、{target}の側に静かに声をかけた。": "Instead of {leader} herself, you had a quiet word with {target}.",
    "{level}。その功績を永久保存版で振り返る": "{level}. A permanent record of everything she achieved",
    "{level}入り": "Inducted into {level}",
    "{names}。第{w}週、大会導入の直後に代表3名と出場順を決定します。": "{names}. In Week {w}, right after the tournament opens, you choose your three representatives and their order.",
    "{names}の{n}人が自然と集まりを作っているようです。": "{names} — {n} of them seem to have drifted into a group of their own.",
    "{names}（{heads}名）を畳み、今後いっさい派閥を作らせない": "Fold {names} ({heads} members) and never allow another faction to form",
    "{names}（{heads}名）を畳む。時が経てば、また新しい群れが生まれる": "Fold {names} ({heads} members). Given time, another group will form",
    "{name} condition": "{name} condition",
    "{name} trust": "{name} trust",
    "{name} {n}枠": "{name} {n} slots",
    "{name} → {ringleader}派": "{name} → {ringleader} Group",
    "{name} → リーダー rivalry": "{name} → leader rivalry",
    "{name} → 旧リーダー 因縁": "{name} → former leader grudge",
    "{name} → 旧リーダー 絆": "{name} → former leader bond",
    "{name} が去った。": "{name} has left.",
    "{name} が引退した。": "{name} has retired.",
    "{name} が持ち込んだ舞台が、今日のカードに組み込まれた。": "The match {name} brought in has been worked into today's card.",
    "{name} に与える休暇の長さを決める。長いほど心身は癒えるが、そのぶんリングを空ける。": "Decide how long {name}'s leave runs. The longer it is, the more she heals — and the longer the ring goes without her.",
    "{name} の直訴を受けたが、メンバー編成が整わず実現できなかった。": "{name} came to you directly, but the lineup could not be put together in time.",
    "{name} の直訴を見送った。": "You passed on {name}'s direct appeal.",
    "{name} への支給額の起案が上がっている。いくら積むかは、社長の判断ひとつ。": "A proposal for {name}'s payment is on your desk. How much to put up is your call alone.",
    "{name} らは次の自団体興行を組む前に、{org}の興行へ遠征する。": "{name} and the others will travel to {org}'s show before your next home show.",
    "{name} メンバー trust": "{name} member trust",
    "{name} メンバー間 bond": "{name} member-to-member bond",
    "{name} メンバー間 絆": "{name} member-to-member bond",
    "{name} リーダー trust": "{name} leader trust",
    "{name} 下位{n}名 trust": "{name} bottom {n} trust",
    "{name} 人気": "{name} popularity",
    "{name} 内 / 外 絆": "{name} inside / outside bond",
    "{name} 内部対立": "{name} internal conflict",
    "{name} 勝": "{name} wins",
    "{name} 勝利": "{name} wins",
    "{name} 勢い": "{name} momentum",
    "{name} 求心力 (mem→leader bond)": "{name} pull (mem→leader bond)",
    "{name} 注目選手": "{name} — wrestlers to watch",
    "{name} 生存": "{name} survives",
    "{name} 知名度": "{name} renown",
    "{name} 結束": "{name} cohesion",
    "{name} 追加人気": "{name} bonus popularity",
    "{name}――派閥内の力学が今夜、リング上で決着する。": "{name} — tonight the balance of power inside the faction is settled in the ring.",
    "{name}、殿堂入り": "{name} enters the Hall of Fame",
    "{name}、殿堂入り——{org}の一時代に幕": "{name} enters the Hall of Fame — the curtain falls on an era of {org}",
    "{name}から挑戦状が届いています": "A challenge letter has arrived from {name}",
    "{name}が{fin}で勝利。": "{name} wins by {fin}.",
    "{name}が、全国統一王者の待つ敵地へ向かっています。": "{name} is on her way into enemy territory, where the unified national champion is waiting.",
    "{name}が、頂点のベルトを手にした。": "{name} has taken the title at the top.",
    "{name}がチームを去りました": "{name} has left the team",
    "{name}がロスターに加わりました！": "{name} has joined the roster!",
    "{name}が出場不能！": "{name} cannot compete!",
    "{name}が加入しました！(スカウト獲得)": "{name} has signed! (scouted)",
    "{name}が団体を去りました": "{name} has left the promotion",
    "{name}が王座防衛に成功した。": "{name} successfully defended the title.",
    "{name}が自然と寄り添っているようです。": "{name} seem to have drifted together on their own.",
    "{name}が選別主義を堂々と語った。賛否両論、燃える誌面となった。": "{name} spoke openly for picking winners. Opinion split, and the story burned across the pages.",
    "{name}と{label}": "{name} and {label}",
    "{name}との一件は、社長の判断で収まった。": "The business with {name} settled on your call.",
    "{name}との契約が成立した": "The contract with {name} is signed",
    "{name}との面談で、迷いは一旦収まった。": "After the meeting with {name}, her doubts settled for now.",
    "{name}に任せた。プレッシャーは肩にのしかかったまま。": "You left it to {name}. The pressure stayed on her shoulders.",
    "{name}に任せる": "Leave it to {name}",
    "{name}に正面から釘を刺した。一瞬の沈黙、それから硬い返事。": "You warned {name} to her face. A moment of silence, then a stiff answer.",
    "{name}に釘を刺した。派閥結成の動きは一旦沈静化した。": "You warned {name} off. The move to form a faction has quieted for now.",
    "{name}に静かに注意した。": "You quietly had a word with {name}.",
    "{name}のリーダーは座を守った。": "{name}'s leader kept her seat.",
    "{name}の亀裂は、とりあえず破裂には至らなかった。": "The crack in {name} did not split open — not yet.",
    "{name}の内紛は自然に任せた。火種は燻ったまま。": "You let the infighting in {name} run its course. The spark is still smoldering.",
    "{name}の動きはリーダーの知るところとなった。{faction}の内側に、新たな火種が燻る。": "{name}'s move reached the leader's ears. A new spark smolders inside {faction}.",
    "{name}の威信は揺らぎ、メンバーの足並みは乱れ始めている。": "{name}'s standing has been shaken, and the members are falling out of step.",
    "{name}の家族的な空気が誌面に出た。柔らかな反響と、ささやかな収入。": "The family feel around {name} made the papers. A warm response, and a modest payday.",
    "{name}の序列が揺らいだ": "The pecking order in {name} has been shaken",
    "{name}の引き留めに成功しました（引き留め {count}/2回目）": "You talked {name} into staying (save {count} of 2)",
    "{name}の待遇相談は受け流した。": "You let {name}'s request about her terms pass.",
    "{name}の意気込みは保留。同じ相手への再打診は当分先になる": "{name}'s enthusiasm is on hold. It will be a while before you can approach the same opponent again",
    "{name}の挑戦は保留。同じ相手からの再打診は当分先になる": "{name}'s challenge is on hold. It will be a while before the same opponent asks again",
    "{name}の挑発を黙って眺めた。客席はざわつきながらも食いついている。": "You watched {name} taunt them without a word. The crowd is restless, and hooked.",
    "{name}の挑発行為に注意した。": "You warned {name} about the taunting.",
    "{name}の格付け争いに介入した。": "You stepped into the fight over rank in {name}.",
    "{name}の模範的対応がファン誌面を飾った。好感度と収入の両取り。": "{name} handled it perfectly, and the fan pages said so. Goodwill and money both.",
    "{name}の気持ちが前向きになってきた": "{name} is starting to feel better about things",
    "{name}の獲得に失敗…": "You failed to sign {name}...",
    "{name}の結束を見守った。輪の外には少し距離が残った。": "You watched {name} close ranks. A little distance remains outside the circle.",
    "{name}の評価要求は受け流した。": "You let {name}'s demand for recognition pass.",
    "{name}の話を聞く": "Hear {name} out",
    "{name}の詳細を開く": "Open {name}'s details",
    "{name}の貢献を、興行の場で言葉にして認めた。": "You put {name}'s contribution into words, in front of the whole show.",
    "{name}は、王者としてベルトを守り抜いた。": "{name} held on to the title as champion.",
    "{name}はタイトル挑戦資格がありません（OVR上位5位以内 or 最高OVRとの差8以内）": "{name} is not eligible to challenge for a title (top 5 in OVR, or within 8 of the highest OVR)",
    "{name}はフリーとなった。": "{name} is now a free agent.",
    "{name}は今の団体に強い忠誠を抱いており、交渉に応じません。": "{name} is fiercely loyal to her current promotion and will not come to the table.",
    "{name}は今夜の屈辱を抱えたまま、リングを去った。火種は、まだ消えない。": "{name} left the ring still carrying tonight's humiliation. The spark has not gone out.",
    "{name}は他団体へ移籍した。": "{name} has transferred to another promotion.",
    "{name}は後を継いだが、派閥内の動揺は深く、一度大きく揺らいだ。": "{name} took over, but the faction was badly shaken and wavered hard.",
    "{name}は数日まとまって過ごし、絆と体調が整った。": "{name} spent a few days together, and both bonds and condition came around.",
    "{name}は深い傷を負い、夜の闇に消えていった。再起できるかは、誰にも分からない。": "{name} was badly hurt and disappeared into the dark. Whether she comes back, no one knows.",
    "{name}は現在、外部コーチとして招聘期間中のため雇用できません": "{name} cannot be hired right now — she is in the middle of an outside coaching stint",
    "{name}は誌面で次の標的を名指しした。火種は派閥外へと撒かれた。": "{name} named her next target in print. The spark has been scattered beyond the faction.",
    "{name}を一度休ませる判断をした。": "You decided to give {name} a rest.",
    "{name}を中心とした集まりを静かに見守ることにした。": "You decided to watch the group forming around {name} in silence.",
    "{name}を中心に派閥「{surname}派」が旗揚げされた（{arch}）。": "A faction has formed around {name}: the {surname} Group ({arch}).",
    "{name}を後押し": "Push {name}",
    "{name}を解任しますか？\\n担当選手のアサインも解除されます": "Dismiss {name}?\\nHer assigned wrestlers will be unassigned too",
    "{name}コーチを、誰に付ける。4週間の指導になる。指導との相性までは、始めてみないと分からない。": "Who do you put Coach {name} with? It is a four-week assignment. Whether the fit works, you will not know until it starts.",
    "{name}コーチ招聘中 — 練習効果アップ(残{w}週)": "Coach {name} on retainer — training boosted ({w} weeks left)",
    "{name}優位 +{diff}": "{name} ahead +{diff}",
    "{name}優位 {diff}": "{name} ahead {diff}",
    "{name}内の固まりを軽くたしなめた。": "You lightly chided the clique inside {name}.",
    "{name}内の対決は別カードに振り替えた。火種はそのまま残った。": "You moved the match inside {name} to another card. The spark stayed where it was.",
    "{name}内の対決を組む方針を固めた。次の興行のカード編成で、どこに置くかは社長次第だ。": "You settled on booking the match inside {name}. Where it goes on the next show's card is up to you.",
    "{name}内の格付け争いはそのまま続いている。": "The fight over rank inside {name} goes on.",
    "{name}派（{arch}）": "{name} Group ({arch})",
    "{name}激励": "Encourage {name}",
    "{name}陣": "{name}'s side",
    "{name}（{cap}席）": "{name} ({cap} seats)",
    "{name}（キャパ {cap}人 ／ 費用 {cost}万）": "{name} (capacity {cap} / cost ¥{cost}0k)",
    "{name}（リーダー）trust": "{name} (leader) trust",
    "{name}（動揺）": "{name} (shaken)",
    "{n} / {max}名": "{n} / {max}",
    "{n}/{cap}名": "{n}/{cap}",
    "{n}/{max}枠": "{n}/{max} slots",
    "{n}人": "{n} wrestlers",
    "{n}件": "{n}",
    "{n}位": "#{n}",
    "{n}名": "{n} wrestlers",
    "{n}名トーナメントの進行データを保持しています。大会画面に戻って進行を続けてください。": "A {n}-wrestler tournament is still in progress. Go back to the tournament screen to continue it.",
    "{n}名在籍": "{n} on the roster",
    "{n}年目": "Year {n}",
    "{n}度目の防衛": "Defense #{n}",
    "{n}度目の防衛成功。王座は、なおその手にある。": "Defense #{n} successful. The title is still in her hands.",
    "{n}期": "{n} seasons",
    "{n}枠": "{n} slots",
    "{n}興行": "{n} shows",
    "{n}試合の団体対決": "A {n}-match promotion showdown",
    "{n}連勝中": "{n}-match win streak",
    "{n}連敗中": "{n}-match losing streak",
    "{n}週": "{n} weeks",
    "{n}週+": "{n} weeks+",
    "{n}週間のスランプを乗り越えた！": "She is out of a {n}-week slump!",
    "{n}週間の低迷から立ち直った！": "She is back after {n} weeks in the doldrums!",
    "{n}防衛": "{n} defenses",
    "{old} ―― {new}。看板が、今夜書き換わった。": "{old} — {new}. Tonight the marquee was rewritten.",
    "{org} が獲得": "{org} takes it",
    "{org} の {champ} に対して挑戦状を叩きつけます。": "You are throwing down a challenge letter to {org}'s {champ}.",
    "{org} 所属": "With {org}",
    "{org}が獲得！": "{org} takes it!",
    "{org}との<span class=\"marker danger\">遺恨</span>は、まだ終わっていない": "The <span class=\"marker danger\">bad blood</span> with {org} is not finished",
    "{org}にはまだ年代記が存在しません。": "{org} has no chronicle yet.",
    "{org}の<span class=\"marker danger\">挑発</span>に、どう応えるか——": "How do you answer {org}'s <span class=\"marker danger\">taunt</span>?",
    "{org}の{fighter}がブレークスルー！": "{org}'s {fighter} has broken through!",
    "{org}の{fighter}がモチベを喪失…": "{org}'s {fighter} has lost her drive...",
    "{org}の{name}が緊急出場": "{org}'s {name} steps in as an emergency replacement",
    "{org}の{name}に王座を奪われた…": "{org}'s {name} has taken the title...",
    "{org}の会場へ乗り込みます": "You are walking into {org}'s venue",
    "{org}の挑戦を受け、次の自団体興行の上位3試合で迎え撃つ": "Accept {org}'s challenge and meet them in the top three matches of your next show",
    "{org}の足跡": "The road {org} has walked",
    "{org}の選手": "{org}'s wrestlers",
    "{org}王座": "{org} title",
    "{org}興行　遠征試合結果": "{org} show — Away match results",
    "{org}（{n}名）": "{org} ({n})",
    "{outlet}からの{label}オファー": "A {label} offer from {outlet}",
    "{period}の給与支払い": "Payroll for {period}",
    "{plan}が組まれた。{a}と{b}は手を組んで観客を沸かせた。": "{plan} was booked. {a} and {b} teamed up and brought the house down.",
    "{plan}が組まれる。両派閥 勢い <strong>+5〜+8</strong>／メンバー間 bond <strong>+1〜+3</strong>": "{plan} will be booked. Both factions' momentum <strong>+5 to +8</strong>/member-to-member bond <strong>+1 to +3</strong>",
    "{range} 累計": "{range} total",
    "{rank}位 {name} {pts}": "#{rank} {name} {pts}",
    "{round} 第{n}試合　結果": "{round} Match {n} — Result",
    "{round}・第{n}フォール": "{round} · Fall {n}",
    "{season}-{week}号": "Issue {season}-{week}",
    "{season}-{week}号 紙面より": "From issue {season}-{week}",
    "{season}年": "Year {season}",
    "{season}年目 年度末 — オフシーズン {offWeek}/4": "End of Year {season} — Off-season {offWeek}/4",
    "{season}年目 総括": "Year {season} in Review",
    "{season}年目: {pop}": "Year {season}: {pop}",
    "{sign}{v}万": "{sign}¥{v}0k",
    "{src}・残{w}週": "{src} · {w} weeks left",
    "{stat}を重点に指導中": "Focusing her coaching on {stat}",
    "{s}年目 末": "End of Year {s}",
    "{target}は{to}へ移っていった。{from}の空気は凍りついている。": "{target} moved over to {to}. The air in {from} has frozen.",
    "{target}：{from} → {to}": "{target}: {from} → {to}",
    "{team} {pos}を選択": "Choose {team} {pos}",
    "{tier}・{name}に勝利！": "Beat {tier} {name}!",
    "{tier}・{name}に敗北…悔しさをバネに這い上がれ。": "Lost to {tier} {name}... let it sting, then climb back.",
    "{tier}級": "Class {tier}",
    "{total}件中 最新{shown}件": "Latest {shown} of {total}",
    "{v}万": "¥{v}0k",
    "{wanted}を探すよう秘書に頼んだ。次の顔ぶれの入れ替わりで返事が来る": "You asked your secretary to look for {wanted}. Word comes back when the names refresh",
    "{wa}勝-{wb}勝": "{wa}-{wb}",
    "{winner}が{loser}を下し、リーダーの威信は保たれた。{faction}内の火種は試合で清算された。": "{winner} beat {loser}, and the leader's standing held. The spark inside {faction} was settled in the ring.",
    "{winner}が{loser}を下した。{faction}内の火種は試合で清算された。": "{winner} beat {loser}. The spark inside {faction} was settled in the ring.",
    "{w}勝{l}敗": "{w}-{l}",
    "{w}週": "{w} weeks",
    "{years}（{n}シーズン）": "{years} ({n} seasons)",
    "{year}年度 新人交渉、本日開幕": "Year {year} rookie negotiations open today",
    "× 敗北": "× Loss",
    "×0.7 減衰": "×0.7 decay",
    "×{n}週": "×{n} weeks",
    "— 4 位 以 下 ・ 追 走 集 団 —": "— 4th and Below · The Chasing Pack —",
    "— あなたの判断 —": "— Your Call —",
    "— そ の 夜 —": "— That Night —",
    "— クリア間近！": "— Almost there!",
    "— シーズン{s}終了 —": "— End of Season {s} —",
    "— タップで続行 —": "— Tap to Continue —",
    "— チャンピオンとして自動エントリー": "— Entered automatically as champion",
    "— 了 解 —": "— Understood —",
    "— 他の選手と交渉中": "— In talks with another wrestler",
    "— 会 場 入 り —": "— Arriving at the Venue —",
    "— 倒産まで推定{w}週": "— About {w} weeks from going under",
    "— 取 消 —": "— Cancel —",
    "— 契約を見送る —": "— Pass on the Contract —",
    "— 戻 る —": "— Back —",
    "— 才能の壁を、一枚だけ超えた —": "— One wall of talent, broken through —",
    "— 敗者の心 —": "— The Loser's Heart —",
    "— 次 へ —": "— Next —",
    "— 決 裁 す る —": "— Approve —",
    "— 沈 黙 —": "— Silence —",
    "— 目撃する —": "— Witness It —",
    "— 移 動 中 —": "— On the Road —",
    "— 素 晴 ら し い —": "— Magnificent —",
    "— 続 け る —": "— Continue —",
    "— 編集長 {name}": "— Editor-in-chief {name}",
    "— 膠 着 —": "— Deadlock —",
    "— 見 届 け る —": "— See It Through —",
    "— 見 送 る —": "— Pass —",
    "— 送 り 出 す —": "— Send Her Off —",
    "— 選手選択 —": "— Choose a Wrestler —",
    "— 選択 —": "— Select —",
    "— 閉 じ る —": "— C l o s e —",
    "——ロッカールームの若手が、先輩たちの顔色を窺うようになった。": "—The young ones in the locker room have started reading their seniors' faces.",
    "……わかった": "...All right",
    "…見殺し": "...Left her to it",
    "※ PPVまでに負傷した場合、自動的に代理選手が出場します": "※ If she is injured before the PPV, a replacement is entered automatically",
    "※ あとから変更できます": "※ You can change this later",
    "※ エントリー後の変更はできません": "※ Entries cannot be changed once submitted",
    "※ レンタル選手はエントリーできません": "※ Loan wrestlers cannot be entered",
    "※ 休暇中の試合には欠場します": "※ She will miss any matches during her leave",
    "※ 大会当日までに負傷した場合は自動で補充されます。未確定のまま大会週を迎えた場合はおまかせ編成で出場します。": "※ Anyone injured before the day of the tournament is replaced automatically. If the tournament week arrives with slots unconfirmed, they are filled by auto booking.",
    "※ 翌シーズンまで満額、その後毎年半減。1pt未満で消滅。": "※ Full value through the following season, then halved every year after. It disappears below 1pt.",
    "※ 記載の能力値は各選手の能力基準値。潜在能力・成長タイプ・体調・戦績は、本ファイルには記載されない。": "※ The stats listed here are each wrestler's base values. Potential, growth type, condition and record are not in this file.",
    "※ 選手のアサインは「🏋️ 育成」画面で行えます ｜ コーチ名タップで詳細": "※ Assign wrestlers on the 🏋️ Training screen | Tap a coach's name for details",
    "※ 閉じた後もロスター閲覧・関係性マップ等は確認できます。<br>※ 週送り（次シーズン進行）はできません。": "※ You can still browse the roster, the relationship map and so on after closing.<br>※ You cannot advance the week or move to the next season.",
    "※興行カード登録中のため解雇できません": "※ She is booked on the card and cannot be released",
    "※逆もあります。上位団体があなたの選手に引き抜きオファーを出してくることも。日頃の信頼が防波堤になります。": "※ It cuts both ways. Bigger promotions will make offers to your wrestlers too. The trust you build day to day is the seawall.",
    "← {name} への感情": "← Feelings toward {name}",
    "← 団体に戻る": "← Back to the Promotion",
    "← 戻る": "← Back",
    "← 第{n}章と SEASON {start}–{end} で重なる": "← Overlaps Chapter {n} across SEASON {start}–{end}",
    "← 週画面に戻る": "← Back to the Week",
    "↑ 強い  ● サイズ=OVR  / クリックで詳細 / サイドバーで団体表示": "↑ Stronger  ● size = OVR  / click for detail / promotions listed in the sidebar",
    "→ {name} への感情": "→ Feelings toward {name}",
    "− 最小化": "− Minimize",
    "≫ スキップ": "≫ Skip",
    "⏩ スキップで確定": "⏩ Skip and Confirm",
    "⏭ スキップ": "⏭ Skip",
    "⏳ いつでも使用可能（温存OK）\n": "⏳ Usable at any time (fine to hold on to it)\n",
    "⏳ 交渉中": "⏳ In Talks",
    "⏳{n}週": "⏳{n} weeks",
    "⏳{n}週後": "⏳ in {n} weeks",
    "─── 契約 ───": "─── Contract ───",
    "─── 引退 ───": "─── Retirement ───",
    "━━ {n}年間の軌跡 ━━": "━━ The Path of {n} Years ━━",
    "━━ キャリアハイライト ━━": "━━ Career Highlights ━━",
    "━━ 通算実績 ━━": "━━ Career Totals ━━",
    "└ 担当選手なし": "└ No wrestlers assigned",
    "▎ 入札卓 ▎": "▎ Bidding Table ▎",
    "■ ブランド収入": "■ Brand Revenue",
    "■ 興行収入": "■ Show Revenue",
    "▲ 1位": "▲ 1st",
    "△ 両者譲らず、DRAW": "△ Neither gives an inch — DRAW",
    "△ 挑戦": "△ Challenge",
    "△苦手": "△ Weak",
    "▶ 次へ進む": "▶ Next",
    "▶ 経営画面へ": "▶ To the Office",
    "▼ クリックで進む": "▼ Click to Continue",
    "▼ 自団体": "▼ Your Promotion",
    "◀ 前へ": "◀ Previous",
    "◀ 次の号": "◀ Next Issue",
    "◆ ドラフト速報 ◆": "◆ Draft Bulletin ◆",
    "○ 万能指導": "○ All-round coaching",
    "○ 勝利": "○ Win",
    "◎ 安全": "◎ Safe",
    "★ メインイベント": "★ Main Event",
    "★ 指名する候補を選んでください": "★ Choose the prospect to pick",
    "★ 殿堂入り": "★ Hall of Fame",
    "★ 自団体 第{n}代表": "★ Your promotion — representative {n}",
    "★ 選択中": "★ Selected",
    "★★ ゴールド殿堂": "★★ Gold Hall of Fame",
    "★★★ レジェンド": "★★★ Legend",
    "★適性◎": "★ Great fit",
    "⚔ 2面 団体比較": "⚔ Page 2 — Promotion Comparison",
    "⚔ F09 派閥対抗戦のため、この試合の選手は変更できません": "⚔ F09 faction war — the wrestlers in this match cannot be changed",
    "⚔ {faction}内対決の予約": "⚔ Booked: a match inside {faction}",
    "⚔ この選手は挑戦試合への出場が決まっています": "⚔ This wrestler is already booked for a challenge match",
    "⚔ 他団体が注目 — 競合時: {n}万": "⚔ Rival promotions are watching — if contested: ¥{n}0k",
    "⚔ 他団体との競合発生！": "⚔ A rival promotion is bidding too!",
    "⚔ 他団体挑戦シリーズ": "⚔ Rival Promotion Challenge Series",
    "⚔ 他団体挑戦（固定）": "⚔ Rival promotion challenge (locked)",
    "⚔ 他団体注目": "⚔ Rivals watching",
    "⚔ 受けて立つ": "⚔ Accept the Challenge",
    "⚔ 奪還挑戦状の発行": "⚔ Issue a Challenge to Reclaim the Title",
    "⚔ 宿敵戦勝利": "⚔ Beat a nemesis",
    "⚔ 対 抗 戦 ・ 代 表 選 出": "⚔ Interpromotional Match · Choosing Representatives",
    "⚔ 対戦要求": "⚔ Match Demand",
    "⚔ 対抗戦": "⚔ Interpromotional Match",
    "⚔ 対抗戦 第{n}試合": "⚔ Interpromotional Match {n}",
    "⚔ 序列戦・決着": "⚔ Ranking Match · Settled",
    "⚔ 抗 争 の 勃 発": "⚔ The Feud Erupts",
    "⚔ 挑戦状": "⚔ Challenge Letter",
    "⚔ 挑戦状によるメインイベント": "⚔ Main event from a challenge letter",
    "⚔ 挑戦試合": "⚔ Challenge Match",
    "⚔ 挑戦試合の上位3枠は固定です": "⚔ The top three slots are locked for the challenge matches",
    "⚔ 挑戦試合の固定枠はタイトル戦に変更できません": "⚔ A locked challenge-match slot cannot be turned into a title match",
    "⚔ 挑戦試合の固定枠はタッグに変更できません": "⚔ A locked challenge-match slot cannot be turned into a tag match",
    "⚔ 決着": "⚔ Settled",
    "⚔ 決着の夜": "⚔ The Night It Ends",
    "⚔ 派閥内序列戦": "⚔ Faction Ranking Match",
    "⚔ 派閥内序列戦は固定です": "⚔ The faction ranking match is locked",
    "⚔ 派閥内序列戦（固定）": "⚔ Faction ranking match (locked)",
    "⚔ 派閥対抗戦 ・ 結末": "⚔ Faction War · The End",
    "⚔ 派閥対抗戦 ・ 開幕": "⚔ Faction War · The Opening",
    "⚔ 王座奪還の決戦！ {a} vs {b}": "⚔ The fight to reclaim the title! {a} vs {b}",
    "⚔ 直訴の一戦、この興行で決着": "⚔ The match she asked for, settled on this show",
    "⚔ 直訴を受理。次の通常興行週、まず敵地へ向かう": "⚔ Appeal accepted. On your next regular show week, you go to their building first",
    "⚔ 競合": "⚔ Contested",
    "⚔ 第{idx}試合 / {total}": "⚔ Match {idx} of {total}",
    "⚔ 試合情報": "⚔ Match Info",
    "⚔他団体挑戦+{n}": "⚔ Rival promotion challenge +{n}",
    "⚖ ① {name} を選択 → ②右側の選手をクリック": "⚖ ① Select {name} → ② Click a wrestler on the right",
    "⚖ ドラフト": "⚖ Draft",
    "⚖ ドラフトへ": "⚖ To the Draft",
    "⚖ ドラフト交渉": "⚖ Draft Negotiation",
    "⚖ ドラフト終了": "⚖ Draft Complete",
    "⚖ 決着つかず": "⚖ Nothing Settled",
    "⚙ 派閥内に火種": "⚙ A spark inside the faction",
    "⚙️ 管理": "⚙️ Manage",
    "⚙️ 設定": "⚙️ Settings",
    "⚠ カードが読み込めていません。画面を作り直しました。もう一度お試しください": "⚠ The card could not be loaded. The screen has been rebuilt — please try again",
    "⚠ ロスター超過のお知らせ": "⚠ Your roster is over the limit",
    "⚠ 不仲": "⚠ Bad blood",
    "⚠ 両方の選手が埋まっている試合が1つもありません": "⚠ Not one match has both wrestlers filled in",
    "⚠ 挑戦試合の出場メンバーが揃わないため、予約を解除しました": "⚠ The challenge match booking was cancelled — the wrestlers could not be assembled",
    "⚠ 挑戦試合の出場条件が整わないため、予約を解除しました": "⚠ The challenge match booking was cancelled — its conditions were not met",
    "⚠ 特別興行につき今回は判定されません（次の通常興行へ持ち越し）": "⚠ This is a special show, so it is not judged this time (carried over to the next regular show)",
    "⚠ 特別興行につき今回は組み込まれません（次の通常興行へ繰り越し）": "⚠ This is a special show, so it is not booked this time (carried over to the next regular show)",
    "⚠ 現在のメインに該当メンバー無し（リーダーが不満を募らせます）": "⚠ No one from the faction is in the current main event (the leader's resentment will build)",
    "⚠ 脅威：ライバルが成長した": "⚠ Threat: a rival has grown",
    "⚠ 衰え": "⚠ Declining",
    "⚠ 遠征メンバーが揃わないため、挑戦試合は中止になりました": "⚠ The challenge match is off — the travelling party could not be assembled",
    "⚠️ 1回限り / 超逸材には使用不可": "⚠️ One use only / cannot be used on elite prospects",
    "⚠️ 指導方針の衝突": "⚠️ Clashing coaching styles",
    "⚠️ 来週は移籍ウィンドウです。信頼ケアの最後のチャンスかもしれません。": "⚠️ The transfer window opens next week. This may be your last chance to shore up trust.",
    "⚠️ 興行処理中に問題が発生しました。状態を復元しました。": "⚠️ Something went wrong while running the show. The previous state has been restored.",
    "⚠️ 興行後の処理で問題が発生しました。状態を復元しました。": "⚠️ Something went wrong after the show. The previous state has been restored.",
    "⚠️ 遠征対抗戦の処理に問題が発生したため、相手選手を除去して予約を解除しました。": "⚠️ Something went wrong with the away interpromotional match, so the opposing wrestlers were removed and the booking cancelled.",
    "⚠️ 選手の解雇は取り消せません": "⚠️ Releasing a wrestler cannot be undone",
    "⚠️ 選手の解雇は取り消せません。": "⚠️ Releasing a wrestler cannot be undone.",
    "⚡ {org}の{name}が乱入！": "⚡ {org}'s {name} storms in!",
    "⚡ ふたりの間に火花が散った": "⚡ Sparks flew between the two of them",
    "⚡ オートセーブ": "⚡ Autosave",
    "⚡ 因縁": "⚡ Grudge",
    "⚡ 決着！": "⚡ Settled!",
    "⚡ 特訓志願": "⚡ Asking for Extra Training",
    "⚡ 突発退団": "⚡ Sudden Departure",
    "⚡因縁+{n}": "⚡ Grudge +{n}",
    "⚡追い込み — 成長が大きく伸びます。そのぶん体調を削り、稀に怪我をします。重ねた無理は消えず、峠にさしかかった年にまとめて返ってきます。": "⚡ Hard drilling — growth jumps. It also cuts into her condition, and now and then it breaks someone. The strain never goes away; it comes back all at once in the year she starts down the far side.",
    "⛔ 枠上限": "⛔ Slots full",
    "⛔ 知名度不足": "⛔ Not enough renown",
    "⛔ 知名度不足（団体人気 {n} 以上で交渉可能）": "⛔ Not enough renown (talks open at promotion popularity {n})",
    "✍ この選手と契約する": "✍ Sign This Wrestler",
    "✍ 契約する": "✍ Sign",
    "✍ 契約セレモニー": "✍ Signing Ceremony",
    "✍ 獲得指名": "✍ Make the Pick",
    "✏️ 名前": "✏️ Name",
    "✒️ 契約交渉": "✒️ Contract Talks",
    "✓ メインに組まれています": "✓ Booked in the main event",
    "✓ 今季交渉済": "✓ Already approached this season",
    "✓ 今週のカードに組まれています": "✓ Booked on this week's card",
    "✓ 現在のメインに該当メンバーが入っています": "✓ A faction member is in the current main event",
    "✕ この選手を外す": "✕ Remove This Wrestler",
    "✕ 危険": "✕ Dangerous",
    "✕ 試合中断": "✕ Stop the Match",
    "✕ 閉じる": "✕ Close",
    "✦ この選手たちの作品をもっと見る ✦": "✦ See more of these wrestlers ✦",
    "✦ 得意スタイル": "✦ Best Style",
    "✨ 初対決": "✨ First Meeting",
    "✨ 名勝負あり": "✨ Classics between them",
    "✨ 宿命の相手との決着がついた": "✨ Settled it with the one she was fated to meet",
    "❌ 諦める": "❌ Give Up",
    "❓ ヘルプ": "❓ Help",
    "❓ 遊び方ガイド": "❓ How to Play",
    "⬇ 衰退期": "⬇ Declining",
    "⬇⬇ 限界": "⬇⬇ At Her Limit",
    "⭐ A級コーチの雇用が解禁されました！": "⭐ You can now hire Class A coaches!",
    "⭐ 次の季節特別興行: 第{w}週": "⭐ Next seasonal special show: Week {w}",
    "⭐ 注目": "⭐ Watch",
    "⭐ 注目候補": "⭐ Prospects to Watch",
    "⭐ 特別興行": "⭐ Special Show",
    "「{a}」が「{b}」を下した。リング上で、ようやく決着がついた。": "{a} beat {b}. In the ring, at last, it was settled.",
    "「{a}」と「{b}」の抗争は、もはや決着の気配すら見せない。終わらない戦いが、団体の空気を重くしていく。": "The feud between {a} and {b} shows no sign of ending. A war with no finish is weighing the promotion down.",
    "「{org}」は活動停止を発表した。": "{org} has announced it is shutting down.",
    "「{org}」は資金難により活動停止を発表した。": "{org} has announced it is shutting down, out of money.",
    "【{feature}】は製品版で解放されます！": "{feature} is unlocked in the full version!",
    "【{feature}】は製品版で遊べます！\nBOOTH で製品版をチェックしてください。": "{feature} is playable in the full version!\nCheck out the full version on BOOTH.",
    "【シーズン終了】": "[Season End]",
    "【実績】": "[Achievement]",
    "【崩壊】": "[Collapse]",
    "【新年号】シーズン{season} 第{week}週": "[New Year Issue] Season {season}, Week {week}",
    "【活動停止】": "[Shut Down]",
    "【表彰】": "[Award]",
    "あと{n}名選んでください": "Choose {n} more",
    "あと{n}週": "{n} weeks to go",
    "あとで": "Later",
    "あと少し！ 4週連続で黒字を出し、資金3,000万以上を維持すれば経営安定化クリア！": "Almost there! Turn a profit four weeks running and hold funds at ¥30,000k or more to clear the stability goal!",
    "あなた": "You",
    "あなたの団体": "Your Promotion",
    "あなたの団体から3名が出場し、1対1を全3試合行います": "Three wrestlers from your promotion compete in three one-on-one matches",
    "あなたの団体の物語は<br>まだ始まったばかりです。<br><br>製品版ではシーズン4以降を<br>無制限にプレイできます。<br><span style=\"color:var(--gold)\">セーブデータはそのまま引き継げます。</span>": "Your promotion's story<br>has only just begun.<br><br>The full version lets you play<br>from Season 4 onward without limit.<br><span style=\"color:var(--gold)\">Your save data carries over as it is.</span>",
    "あなたは新興の女子プロレス団体のオーナーです。": "You own a young women's wrestling promotion.",
    "いいえ": "No",
    "おかえり": "Welcome back",
    "おすすめ": "Recommended",
    "おすすめペア": "Recommended Pair",
    "おまかせ": "Auto",
    "おまかせ選出": "Auto Select",
    "おまかせ（重点なし）": "Auto (no focus)",
    "お引き取り願う": "Show Her Out",
    "かつての因縁": "An old grudge",
    "からの申し入れです。": " has come to you with a request.",
    "が見たい！": "— wants this match!",
    "きょうの紙面": "Today's Paper",
    "ぎくしゃくしている": "Things are awkward",
    "ここで降りる": "Bow Out Here",
    "ここまで燃え広がった対立は、もう言葉では止まらない。火が弱まれば、仲裁の余地も生まれる": "A conflict burning this wide will not be stopped with words. If the fire dies down, there will be room to mediate",
    "この5名でシーズン開始": "Start the season with these five",
    "この{n}名で開戦する": "Go to war with these {n}",
    "この{n}年間、ベルトは{m}人を渡った": "Over these {n} years, the title passed through {m} hands",
    "この{n}年間、ベルトは一度も持ち主を変えなかった": "Over these {n} years, the title never changed hands",
    "このゲームのセーブデータは<span style=\"color:#ffb59a;font-weight:700\">ブラウザのローカルストレージ</span>に保存されます。<br>": "This game saves to <span style=\"color:#ffb59a;font-weight:700\">your browser's local storage</span>.<br>",
    "このコーチのアサイン枠が満員です": "This coach's assignment slots are full",
    "このシーズンの勲章はまだない。<br>※ PPV優勝/MVP/ベストマッチ賞/ジュニアトーナメント優勝/メディア功労賞などで加点。<br>翌シーズンまで満額、その後毎年半減。1pt未満で消滅。": "No honors this season yet.<br>※ Points come from PPV wins, MVP, Best Match, the Junior Tournament and the Media Merit Award, among others.<br>Full value through the following season, then halved every year after. It disappears below 1pt.",
    "このペアに対して斡旋を行いますか？": "Try to patch things up between these two?",
    "この一戦がどれだけ客を呼べるか。両選手の人気と実力に、拮抗・因縁・タイトル戦などの注目度が上乗せされます。": "How many tickets this one can move. Both wrestlers' popularity and strength, plus the interest that comes from an even matchup, a grudge or a title on the line.",
    "この一戦は公式戦として記録される": "This one goes on the official record",
    "この件、社長としてどう扱いますか？": "How do you handle this?",
    "この依頼は出せませんでした": "That request could not be made",
    "この内容で決裁しますか？": "Approve this as written?",
    "この動きについて、社長としてどう扱いますか？": "How do you handle this move?",
    "この合同企画、社長としてどう扱いますか？": "How do you handle this joint project?",
    "この四半期の紹介枠にフリーエージェントはいません": "No free agents are being put forward this quarter",
    "この団体": "This promotion",
    "この団体の歩みは、いくつもの紙面に記録されていきます。": "This promotion's progress will be recorded across many pages.",
    "この団体戦の残り全試合を自動進行し、団体戦の決着画面へ移ります。": "Run the rest of this series automatically and go straight to the result screen.",
    "この団体戦挑戦、社長としてどう答えますか？": "How do you answer this challenge?",
    "この布陣で決勝へ": "To the Final with This Lineup",
    "この布陣で開戦": "Go to War with This Lineup",
    "この挑戦、どう受けますか？": "How do you take this challenge?",
    "この挑戦状、どうしますか？": "What do you do with this challenge letter?",
    "この時代のエース": "The Ace of the Era",
    "この時代の主な出来事": "Major Events of the Era",
    "この時代の二枚看板": "The Era's Two Marquee Names",
    "この時代の同期": "Debut Class of the Era",
    "この時代の外敵": "Outsiders of the Era",
    "この時代の気風はまだ動いています。この章の選手たちが引退したとき、最終的な傾向が確定します。": "The temper of this era is still shifting. It settles for good once the wrestlers in this chapter retire.",
    "この時代の通算": "Era Totals",
    "この書類の発動条件を満たしていません": "The conditions for this document have not been met",
    "この書類は今週すでに決裁済みです。週を進めるとまた検討できます": "This document has already been approved this week. Advance a week and you can take it up again",
    "この書類は対象の選手がまだ受け取ったばかりです": "The wrestler this concerns has only just received it",
    "この期間の収入記録はありません": "No revenue recorded for this period",
    "この期間の支出記録はありません": "No expenses recorded for this period",
    "この期間の記録はまだありません": "Nothing recorded for this period yet",
    "この決裁は実行できませんでした": "That approval could not be carried out",
    "この火種、社長としてどう扱いますか？": "How do you handle this spark?",
    "この熱を、どこに着火させるかは社長の手の中にある。": "Where to set this heat alight is in your hands.",
    "この熱を、社長としてどう扱いますか？": "How do you handle this heat?",
    "この申し入れ、どう受けますか？": "How do you take this offer?",
    "この空気を、社長としてどう扱いますか？": "How do you handle the mood in the room?",
    "この章はまだ書きかけです。旗揚げメンバー全員が引退すると、序章が確定します。": "This chapter is still being written. The prologue is set once every founding member has retired.",
    "この章はまだ書きかけです。選手たちが引退して数年が経つと、章が確定します。": "This chapter is still being written. It is set a few years after these wrestlers retire.",
    "この約束は、次の通常興行のメインで果たされる。": "This promise is kept in the main event of the next regular show.",
    "この編成で開催します。開催後はカードを変更できません。": "The show runs with this card. It cannot be changed once the show begins.",
    "この舞台、組もう": "Book This One",
    "この行動は現在利用できません": "That action is not available right now",
    "この試合の結果を見る": "See the result of this match",
    "この週は遠征対抗戦を実行できません。": "An away interpromotional match cannot be run this week.",
    "この選手たちの活躍が、物語を作っていきます。": "What these wrestlers do is what builds the story.",
    "この選手とは今シーズン既に交渉済みです。": "You have already approached her this season.",
    "この選手にはしばらく約束できない": "You cannot promise her anything for a while",
    "この選手には今、声をかける理由がない": "There is no reason to approach her right now",
    "この選手に響くやり方ではない": "That is not what gets through to her",
    "この選手の交渉から離脱する": "Withdraw from talks for this wrestler",
    "この選手はすでに自団体に所属しています": "She is already on your roster",
    "この選手を中心に見る ›": "Center the map on her ›",
    "こまめにセーブしましょう。こまめに書き出しセーブもしましょう。": "Save often. Export your saves often too.",
    "これは": "This looks like it will be a",
    "しばらく成長が止まるかもしれない": "Her growth may stall for a while",
    "すぐ進む": "Skip Ahead",
    "すでに{name}と約束がある": "You already have a promise with {name}",
    "すでに全枠を開放しています": "Every slot is already open",
    "すでに招聘中のコーチがいます": "You already have a coach on retainer",
    "すでに招聘中のコーチがいます({name}・残{n}週)": "You already have a coach on retainer ({name} · {n} weeks left)",
    "すでに約束がある": "A promise is already in place",
    "すべて解除": "Clear All",
    "そっと結束を後押しする": "Quietly encourage them to close ranks",
    "そのままでも自動で進みます": "It will move on by itself if you leave it",
    "その他": "Other",
    "その他の関係": "Other Relationships",
    "その他指名候補 — {n}名": "Other prospects — {n}",
    "つづき": "Continued",
    "と{faction}の動きについて、社長室での相談です。": " and what {faction} is up to — a matter for the office.",
    "と{faction}の様子について、社長の判断を仰ぎたいとのことです。": " and how {faction} is doing — they would like your decision.",
    "ど う 立 ち 会 い ま す か": "How Will You Witness This?",
    "どうしますか？": "What do you do?",
    "どう介入しますか？": "How do you step in?",
    "どう対応しますか？": "How do you respond?",
    "どこからも指名されなかった選手はフリー市場へ回ります。": "Anyone who goes unpicked moves to the free-agent market.",
    "どちらも屈しない。どちらも勝てない。": "Neither will yield. Neither can win.",
    "どの起案額にも資金が足りません": "You cannot afford any of the proposed amounts",
    "なし": "None",
    "なし（再判定継続）": "None (keep re-checking)",
    "なし（時間に委ねる）": "None (leave it to time)",
    "なし（静観）": "None (stand back)",
    "の指導について": " — about her coaching",
    "の指導期間延長(+2週)": " — coaching extended (+2 weeks)",
    "の挑戦を検討してください": " — consider making a run at it",
    "の集まりになりそうです。": "kind of circle.",
    "ひとつ戻る": "Back One Step",
    "への引き抜き交渉を開始します。": " will be approached about a transfer.",
    "への敵対度": " — hostility",
    "へ加入": " — new member",
    "まだキャリア記録がありません": "No career record yet",
    "まだデータが不足しています（2シーズン以上経過後に表示）": "Not enough data yet (shown after two seasons)",
    "まだ余裕": "Still comfortable",
    "まだ出来事は刻まれていない。": "Nothing has been written down yet.",
    "まだ殿堂入りした選手はいません": "No one has entered the Hall of Fame yet",
    "まだ表には出ていないが、このまま放っておけば派閥が割れるかもしれない。": "It has not surfaced yet, but left alone the faction could split.",
    "まだ記録がありません": "No records yet",
    "まとめてスキップ": "Skip All",
    "まもなく入れ替わる": "Refreshing soon",
    "やっぱりやめる": "Never Mind",
    "やめる": "Cancel",
    "よくやった": "Well done",
    "よそよそしい": "Distant",
    "よろしいですか？": "Are you sure?",
    "わずかに衰えの兆候": "A faint sign of decline",
    "わだかまりが残る": "Something still lingers",
    "わだかまりを残した": "Something was left unsettled",
    "アイドル選手": "Idol wrestler",
    "アップ": "Close-Up",
    "イベント": "Events",
    "イベントデータなし": "No event data",
    "エアリアル": "Aerial",
    "エラー": "Error",
    "エントリー": "Enter",
    "エントリー確定（{a}/{b}名）": "Confirm Entry ({a}/{b})",
    "エース": "Ace",
    "エース候補にアサインすれば、成長がまるで違います。": "Put a coach on your future ace and the growth is a different thing entirely.",
    "エース候補をメインに据えて高い試合評価を。同じ相手と当て続ければ、因縁も育ちます。": "Put your future ace on top and chase a high match rating. Keep booking her against the same opponent and a grudge grows too.",
    "エース力": "Ace Power",
    "エース力=看板3人のOVR (TOP3平均÷100×100) / 層の厚み=控え5人のOVR (4〜8位平均÷80×100、不足枠は0扱い) / 集客力=団体人気そのまま / タイトル力=看板5人の人気 (TOP5平均人気÷80×100)": "Ace Power = OVR of your top 3 (TOP3 average ÷100×100) / Depth = OVR of the next 5 (average of ranks 4–8 ÷80×100, empty slots count as 0) / Draw = promotion popularity as-is / Title Power = popularity of your top 5 (TOP5 average popularity ÷80×100)",
    "エース密着": "Up Close with the Ace",
    "エース対決": "Ace vs Ace",
    "エース級": "Ace-class",
    "エース級の選手が引退し、ひとつの世代が終わったとき、<br>最初の章が記録されます。": "When an ace-class wrestler retires and a generation closes,<br>the first chapter is written.",
    "オフシーズン {offW}/4": "Off-season {offW}/4",
    "オフシーズン {w}/4": "Off-season {w}/4",
    "オフシーズン — 案件なし": "Off-season — nothing on the desk",
    "オフシーズンには約束できない": "You cannot make promises in the off-season",
    "オフシーズンは頼めない": "You cannot ask during the off-season",
    "オフシーズンへ →": "To the Off-season →",
    "オフシーズンレポート": "Off-season Report",
    "オフシーズン中はレンタルできません": "Loans are not available during the off-season",
    "オフシーズン中は依頼できません": "Requests cannot be made during the off-season",
    "オフシーズン中は決裁できません": "Approvals cannot be made during the off-season",
    "オフシーズン突入": "Into the Off-season",
    "オフシーズン第{n}週へ →": "To Off-season Week {n} →",
    "オートセーブ": "Autosave",
    "オートセーブからロードしますか？\\n現在の進行は失われます。": "Load from the autosave?\\nYour current progress will be lost.",
    "オートセーブの読み込みに失敗しました。": "The autosave could not be loaded.",
    "オートセーブデータなし（週を進めると自動保存されます）": "No autosave yet (it saves automatically when you advance a week)",
    "オールラウンダー": "All-rounder",
    "オールラウンド": "All-round",
    "カットイン！": "Cut-in!",
    "カメラ": "Camera",
    "カード": "Card",
    "カードに在籍していない選手が含まれていたため自動で解除しました。カードを確認してください。": "The card included wrestlers who are no longer on the roster, so it was cleared automatically. Please check the card.",
    "カードのどこか(メイン/セミ/中盤)に組んでください": "Book it somewhere on the card (main, semi-main or midcard)",
    "カード登録中": "Booked on the card",
    "カード編成不成立": "The card could not be assembled",
    "カード魅力": "Card Appeal",
    "キャパ: {cap}人": "Capacity: {cap}",
    "キャリア{n}年目": "Career year {n}",
    "キャリア年表": "Career Timeline",
    "キャンセル": "Cancel",
    "クリックで代表を決定します": "Click to lock in your representatives",
    "クリックで次へ": "Click to continue",
    "クリックで進む": "Click to advance",
    "グッズ": "Merch",
    "グッズ収入": "Merch Income",
    "グッズ収入がアップします": "Merch income goes up",
    "グッズ収入がアップします（2週間）": "Merch income goes up (2 weeks)",
    "グラウンド攻撃": "Ground Attack",
    "グラップラー": "Grappler",
    "グレード": "Grade",
    "グレード: 全て": "Grade: All",
    "ゲームデザイン・開発": "Game Design & Development",
    "ゲームログ": "Game Log",
    "コスト": "Cost",
    "コスト: {cost}万": "Cost: ¥{cost}0k",
    "コンディション": "Condition",
    "コーチ": "Coach",
    "コーチ: {n}名": "Coaches: {n}",
    "コーチ: なし": "Coach: none",
    "コーチは現在最大{n}名まで（枠拡張で増加）": "You can have up to {n} coaches for now (expand your slots for more)",
    "コーチを介して{leader}の状態を確かめ、派閥外への目配りも忘れなかった。": "Through the coach you checked on {leader}, and kept an eye on things outside the faction too.",
    "コーチ効果": "Coach Effect",
    "コーチ同席で対応": "Handle it with a coach present",
    "コーチ同席で無難な記事に収まった。色は薄いが、ささやかな実りはあった。": "With a coach in the room the piece came out safe. Pale, but it bore a little fruit.",
    "コーチ招聘中 — 練習効果アップ(残{w}週)": "Guest coach on site — training boosted ({w} weeks left)",
    "コーチ招聘中 残り{n}週": "Guest coach on site — {n} weeks left",
    "コーチ未雇用 — {link}から雇用できます": "No coach hired — you can hire one from {link}",
    "コーチ枠を拡張しました。": "Coach slots expanded.",
    "コーチ経由ケア": "Care via coach",
    "コーチ経由調整": "Adjustment via coach",
    "コーチ給与（{n}名）": "Coach salaries ({n})",
    "コーチ能力:": "Coach ability:",
    "コーチ雇用には決裁枠 ⚡{cost} が必要です（現在: ⚡{cur}）": "Hiring a coach costs ⚡{cost} in approvals (you have ⚡{cur})",
    "ゴングを待っています": "Waiting for the bell",
    "ゴールド殿堂": "Gold Hall of Fame",
    "サウンド ON/OFF": "Sound On/Off",
    "サブミッション": "Submission",
    "シングル": "Singles",
    "シングルに戻す": "Back to Singles",
    "シングル挑戦の直訴": "Direct appeal for a singles match",
    "シーズン": "Season",
    "シーズン {n}": "Season {n}",
    "シーズン{n} 契約更新": "Season {n} Contract Renewals",
    "シーズン{season} オフ第3週": "Season {season}, Off-Season Week 3",
    "シーズン{season} オフ第{week}週": "Season {season}, Off-Season Week {week}",
    "シーズン{season} 第{week}週": "Season {season}, Week {week}",
    "シーズン{s} オフ第{w}週": "Season {s}, Off-Season Week {w}",
    "シーズン{s} 成長ログ": "Season {s} Growth Log",
    "シーズン{s} 第{w}週": "Season {s}, Week {w}",
    "シーズンレポートへ →": "To the Season Report →",
    "シーズン履歴": "Season History",
    "シーズン進行中": "Season in progress",
    "シーズン開幕": "Season Opening",
    "シーズン開幕へ": "To the Season Opening",
    "ジュニアトーナメント": "Junior Tournament",
    "ジュニアトーナメント 優勝": "Junior Tournament — Winner",
    "ジュニアトーナメントは出場条件を満たす選手が足りないため開催されませんでした。": "The Junior Tournament was not held: too few wrestlers met the entry conditions.",
    "ジュニアトーナメント優勝": "Junior Tournament Winner",
    "ジュニア王者": "Junior Champion",
    "スキップ": "Skip",
    "スキップ →": "Skip →",
    "スケジュール": "Schedule",
    "スコア": "Score",
    "スタイル": "Style",
    "スタイル: 全て": "Style: All",
    "スタイルで絞り込む": "Filter by style",
    "スタッフの声": "Staff Voices",
    "スタッフ募集": "Staff Openings",
    "スタッフ募集 →": "Staff Openings →",
    "スタミナ": "Stamina",
    "スタンド画像または名前で詳細を確認": "Click the photo or the name to see details",
    "ストライカー": "Striker",
    "スピード": "Speed",
    "スランプ": "Slump",
    "スランプ中の選手だ。今日は、少し時間を取ろう。": "She's in a slump. Take a little time with her today.",
    "スランプ中の選手ではありません": "She is not in a slump",
    "スロット {n}": "Slot {n}",
    "スロット{n}からロードしますか？\\n現在の進行は失われます。": "Load from slot {n}?\\nYour current progress will be lost.",
    "スロット{n}に上書きセーブしますか？": "Overwrite the save in slot {n}?",
    "スロット{n}のデータを削除しますか？": "Delete the data in slot {n}?",
    "スロット{slot}の表示名を設定します。空欄のまま決定すると名前を解除します。": "Set a display name for slot {slot}. Leave it blank and confirm to clear the name.",
    "セミファイナル": "Semi-Final",
    "セミファイナル {a} vs {b}": "Semi-Final: {a} vs {b}",
    "セーブ": "Save",
    "セーブに失敗しました: ": "Save failed: ",
    "セーブデータがありません": "No save data",
    "セーブデータについて必ずお読みください": "Please read this about your save data",
    "セーブデータの読み込みに失敗しました。コンソールを確認してください。": "Failed to load the save data. Check the console.",
    "セーブデータをファイルとして書き出し、別のデバイスやブラウザに移行できます。<br>": "You can export your save data as a file and move it to another device or browser.<br>",
    "セーブ名を変更": "Rename Save",
    "タイ": "Tie",
    "タイトルに戻る": "Back to Title",
    "タイトルへ": "To Title",
    "タイトルへ戻る（ESC可）": "Back to title (ESC works too)",
    "タイトルマッチ": "Title Match",
    "タイトルマッチの挑戦者が差し替わった！\nOVR {ovr} の強敵が王座を狙う！": "The title match has a new challenger!\nAn OVR {ovr} threat is coming for the title!",
    "タイトルマッチは12週に1回のみ開催できます（あと{n}週）": "A title match can only be held once every 12 weeks ({n} weeks to go)",
    "タイトルマッチはチャンピオンを含む必要があります": "A title match must include the champion",
    "タイトル力": "Title Power",
    "タイトル戦": "Title Match",
    "タイトル戦経験<strong>あり</strong>": "Title bout experience: <strong>yes</strong>",
    "タイトル挑戦の直訴、休養申請、不満の爆発……社長の判断を求める出来事が起きます。選択肢に添えられた一言が、結果の手がかりです。": "A direct appeal for a title shot, a request for time off, a flare-up of discontent... things will come up that need your call. The line under each option is your clue to how it will land.",
    "タイトル王者": "Title Holder",
    "タイトル王者 1位": "Title Holder — 1st",
    "タイムアップ — 決着つかず": "Time limit — no decision",
    "タイムラインに記録された抗争イベントはまだありません": "No feud events have been recorded on the timeline yet",
    "タッグ": "Tag",
    "タッグや日々の交わりの中で育ちます。深い絆は成長を後押しし、土壇場の踏ん張りに効きます。": "It grows through tag teams and everyday contact. A deep bond speeds growth and holds up when it matters most.",
    "タッグマッチ": "Tag Match",
    "タッグマッチデータの受信を待機中…": "Waiting for tag match data...",
    "タッグ枠同士は合体できません": "Two tag slots cannot be merged",
    "タッグ王者": "Tag Champions",
    "タッチ": "Tag!",
    "タップして次へ": "Tap to continue",
    "タップして続きを見る": "Tap to see the rest",
    "タップして進む": "Tap to advance",
    "タップすると組み直せます。": "Tap to rearrange.",
    "タレント活動": "Media Appearances",
    "ダブルチーム！": "Double team!",
    "チーム": "Team",
    "チームA": "Team A",
    "チームB": "Team B",
    "テクニシャン": "Technician",
    "テクニック": "Technique",
    "テレビの前で": "In front of the TV",
    "テレビの明かりを消す。": "You switch off the TV.",
    "テレビ中継を見る": "Watch the broadcast",
    "テレビ観戦": "Watch on TV",
    "データの読み込みに失敗しました。ファイルが破損している可能性があります。": "Failed to load the data. The file may be corrupted.",
    "ドラフト": "Draft",
    "ドラフトへ": "To the Draft",
    "ドラフト会議へ →": "To the Draft →",
    "ドラフト完了": "Draft Complete",
    "ドラフト結果": "Draft Results",
    "ドラフト速報": "Draft Bulletin",
    "ニューゲーム": "New Game",
    "ニュートラル": "Neutral",
    "ネットワーク": "Network",
    "ハイリターン": "High Return",
    "バックナンバー {n}/{total}": "Back Issues {n}/{total}",
    "バランス": "Balanced",
    "バランスより、エース候補を1人。団体の顔が育てば興行が回り始めます。": "Better than a balanced roster: one wrestler who can be the ace. Once you have a face for the promotion, the shows start to work.",
    "バランス型": "Balanced",
    "パワー": "Power",
    "パワーファイター": "Power Fighter",
    "ヒート +{n}": "Heat +{n}",
    "ヒール": "Heel",
    "ヒール派閥": "Heel faction",
    "ピーク": "Peak",
    "ファイルの読み込みに失敗しました": "Failed to load the file",
    "ファイルを選択": "Choose File",
    "ファンの声": "Fan Voices",
    "ファンの間に動揺が広がっている（人気{delta}）": "Unease is spreading among the fans (popularity {delta})",
    "フィジカル": "Physical",
    "フォロワー → {name} bond": "Followers → {name} bond",
    "フォーカス": "Focus",
    "フライヤー": "Flyer",
    "フリー": "Free Agent",
    "フリーエージェント": "Free Agent",
    "フリーエージェントとして": "As a free agent",
    "フレッシュ度低": "Low freshness",
    "ブラウザのキャッシュクリア・再インストール・プライベートモード終了で<span style=\"color:#ff7a55;font-weight:700\">データが完全に消失</span>します。<br>": "Clearing your browser cache, reinstalling, or leaving private browsing will <span style=\"color:#ff7a55;font-weight:700\">erase your data completely</span>.<br>",
    "ブランド収入": "Brand Income",
    "ブレークスルー！": "Breakthrough!",
    "ブロウラー": "Brawler",
    "ブロック": "Block",
    "プラン": "Plan",
    "プレイヤー": "Player",
    "プレイヤー団体": "Your promotion",
    "プロフィール": "Profile",
    "プロモ": "Promo",
    "プロモ優先": "Promo Focus",
    "プロモ収入": "Promo Income",
    "プロレス会場のリング": "A wrestling ring in an arena",
    "ベストマッチ": "Best Match",
    "ベスト評価": "Best Rating",
    "ベテラン": "Veteran",
    "ベテラン特集": "Veteran Feature",
    "ベビー": "Face",
    "ベビーフェイス": "Babyface",
    "ペナルティなし": "No penalty",
    "ボンド合計 中立（白）": "Total bond neutral (white)",
    "ボンド合計 低（赤）": "Total bond low (red)",
    "ボンド合計 高（青）": "Total bond high (blue)",
    "ボーナスも清算し、関係が大きく軋む ／ 移籍志願のおそれ": "Settle the bonus too — the relationship strains badly / she may ask for a transfer",
    "ポイント": "Points",
    "ポイント順": "By Points",
    "マインド": "Mind",
    "メイン{n}回出場": "{n} main events",
    "メインイベント": "Main Event",
    "メインイベント(タッグ)": "Main Event (Tag)",
    "メインイベントから上位3試合を固定しています。会場の全{maxMatches}枠のうち、通常カードは残り{regularSlots}枠です。各挑戦試合には集客評価+{appeal}が入ります。": "The top three matches from the main event down are locked. Of the venue's {maxMatches} slots, {regularSlots} are left for regular booking. Each challenge match adds +{appeal} to the draw rating.",
    "メインイベントはシングルマッチのみです": "The main event must be a singles match",
    "メインカード推薦期間": "Main-card recommendation period",
    "メインドラフト": "Main Draft",
    "メイン枠に <strong>{name}</strong> のメンバーを推す約束をしています。": "You promised to push a member of <strong>{name}</strong> into the main event slot.",
    "メイン（先頭の枠）に組まなければ、約束を破ったことになります": "If you don't book it in the main event (the first slot), you break the promise",
    "メディア": "Media",
    "メディア功労賞": "Media Merit Award",
    "メディア収入": "Media Income",
    "メディア収入がアップします": "Media income goes up",
    "メディア取材": "Press Interview",
    "メンタル": "Mental",
    "メンバー": "Members",
    "メンバー trust": "Member trust",
    "メンバー → リーダー 因縁": "Member → leader grudge",
    "メンバー → リーダー 絆": "Member → leader bond",
    "メンバー間 bond": "Member-to-member bond",
    "メンバー間でも私的な交流が戻り始めた。社長の一押しがあれば、抗争は完全に終結する。": "Members have started talking to each other privately again. One push from you and the feud is over for good.",
    "モチベーションを失いかけている。放っておけない。": "She's losing her drive. You can't leave this alone.",
    "モチベ喪失": "Lost drive",
    "モメンタム": "Momentum",
    "ライバル": "Rival",
    "ライバル団体": "Rival Promotion",
    "ライバル団体から挑戦状が届くことがあります。3本勝負または5本勝負の団体戦。勝てば人気と業界での立場が上がり、負ければ痛手を負います。選手が「あの団体とやらせてほしい」と直訴してくることもあります。": "A rival promotion may send you a challenge letter: a best-of-three or best-of-five between the two sides. Win and your popularity and standing in the business go up; lose and it hurts. Sometimes a wrestler will come to you and ask to face a particular promotion.",
    "ライバル団体に隙が生まれた。攻勢のチャンス！": "A rival promotion has left an opening. Time to press!",
    "ライバル心": "Rivalry",
    "ライバル心 ": "Rivalry ",
    "ラストラン状態に入りました。次の興行で引退試合を組みましょう。": "She has entered her last run. Book her retirement match on the next show.",
    "ランキング": "Rankings",
    "ランキング1位到達！ 王者の団体にふさわしい最大契約枠が解放されました。": "You've reached #1 in the rankings! The full contract allowance befitting the top promotion is now unlocked.",
    "ランク": "Rank",
    "リスク:": "Risk:",
    "リスク低め": "Low Risk",
    "リスク指標🟢を目安に。焦って大箱に出ると空席が団体を蝕みます。": "Use the 🟢 risk marker as your guide. Rush into a big room and the empty seats will eat the promotion alive.",
    "リセット": "Reset",
    "リングで語り合おう、と<span class=\"marker danger\">挑戦状</span>を突きつけてきた。": "She has thrust a <span class=\"marker danger\">challenge letter</span> at you: let's settle it in the ring.",
    "リングの上での敬意": "Respect in the ring",
    "リング上": "In the ring",
    "リング上 HP": "In-ring HP",
    "リング上での戦い": "The fight in the ring",
    "リーグ 第{n}試合": "League — Match {n}",
    "リーグ 第{n}試合まで終了": "League — through match {n}",
    "リーグ勝点 +3": "League points +3",
    "リーダー": "Leader",
    "リーダーは社長の裁定を受け入れている": "The leader accepts your ruling",
    "リーダー喪失": "Leader lost",
    "リーダー離脱見込み": "Leader expected to leave",
    "レガシー": "Legacy",
    "レガシー — 積み上げた歴史（上限50pt）": "Legacy — the history you've built (max 50pt)",
    "レポート": "Report",
    "レンタルする": "Take on Loan",
    "レンタル交渉は不成立でした": "The loan talks fell through",
    "レンタル加入！": "Joining on loan!",
    "レンタル可能な選手がいません": "No wrestlers are available on loan",
    "レンタル枠": "Loan Slots",
    "レンタル枠:": "Loan slots:",
    "レンタル枠が満員です": "Your loan slots are full",
    "レンタル枠（{a}/{b}）": "Loan slots ({a}/{b})",
    "レンタル選手はタイトルマッチに出場できません": "Loaned wrestlers cannot appear in title matches",
    "レンタル選手は自律行動します。スケジュールの指定はできません。": "Loaned wrestlers act on their own. You cannot set their schedule.",
    "ロスター全体の士気": "Morale across the roster",
    "ロスター定員を超過": "Roster over capacity",
    "ロスター枠が上限です": "Your roster is at capacity",
    "ロッカールームには、冷たい対立の空気が満ちているようです。": "A cold, hostile air seems to fill the locker room.",
    "ロッカールームに影響が出ました。": "It has affected the locker room.",
    "ロッカールームの緊張は限界に近く、メンバー全員が次の興行のカード編成を待っている。": "Tension in the locker room is near breaking point, and everyone is waiting to see the next show's card.",
    "ロッカールーム代表": "Locker room representative",
    "ロッカー士気": "Locker room morale",
    "ロード": "Load",
    "・タイトルマッチはそれ自体が興行の看板になる": "• A title match is a headline attraction in itself",
    "・タッグ経験{n}": "• Tag experience {n}",
    "・レンタル選手は出場できません": "• Loaned wrestlers cannot take part",
    "・同時レンタルは2〜3枠（ロスター規模による）": "• You can hold 2–3 loans at once (depending on roster size)",
    "・実力の近い者同士は良い試合になりやすい": "• Evenly matched wrestlers tend to have better matches",
    "・相手団体の看板上位3名は借りられません": "• You cannot borrow a promotion's top three marquee names",
    "・費用は前払い一括": "• The fee is paid up front in full",
    "一 年 を 超 え た": "OVER A YEAR",
    "一人": "one wrestler",
    "一旦リセット": "Reset for now",
    "一時+": "Temporary +",
    "一時微減": "Slight temporary dip",
    "一時金{a}万 + 給与+{b}万/週": "Signing bonus ¥{a}0k + salary +¥{b}0k/week",
    "一本線=関係の濃さ<br>敵対ライバル=橙→赤<br>友好ライバル=黄緑→青": "Line weight = how strong the tie is<br>Hostile rivals = orange → red<br>Friendly rivals = yellow-green → blue",
    "一致": "Match",
    "一面トップ": "Front-page lead",
    "一面記事": "Front-page story",
    "万": "×10k",
    "万 ／ 残り資金": "×10k / Remaining funds",
    "万能": "All-round",
    "三人": "three wrestlers",
    "三面": "Page 3",
    "上のスロットの「📥 書出」でファイル保存、下の「読み込む」で復元してください。": "Use 📥 Export on a slot above to save a file, and Load below to restore it.",
    "上へ": "Up",
    "上位3試合で、相手団体の3名と1対1ずつ戦います": "In the top three matches you face three of their wrestlers one-on-one",
    "上位シード待ち": "Awaiting a top seed",
    "上位団体から選手への引き抜きオファーが届いています。各選手への対応を選択してください。": "A bigger promotion has made offers to your wrestlers. Choose how to respond for each of them.",
    "上昇": "Rising",
    "上限": "Max",
    "下 剋 上": "COUP",
    "下の枠と合体してタッグマッチに": "Merge with the slot below to make a tag match",
    "下へ": "Down",
    "下克上 ―― {winner}が{faction}リーダー{loser}を下した。{flavor}。": "Coup — {winner} has brought down {faction} leader {loser}. {flavor}.",
    "不一致": "No match",
    "不参加": "Not entered",
    "不在": "Vacant",
    "不明": "Unknown",
    "不明なイベント": "Unknown event",
    "不満を残した様子": "She seems left unsatisfied",
    "世代": "Generation",
    "両派の対立": "Hostility between the factions",
    "両派の対立は、後戻りできない段階に入った": "The hostility between the factions has passed the point of no return",
    "両派リーダー ・ 一騎打ち": "Both leaders · One-on-one",
    "両派閥 メンバー間 bond": "Both factions' member-to-member bond",
    "両派閥 勢い": "Both factions' momentum",
    "両派閥 関係": "Relations between the factions",
    "両派閥の抗争は、団体公認のメインイベントへ": "The feud between the factions becomes an official main event",
    "両派閥の自発的な交流が実った": "The factions reached out to each other on their own, and it paid off",
    "両派閥メンバー mentalCoeff": "Both factions' members mentalCoeff",
    "両者とも社長への不満を募らせる ／ 士気低下": "Both grow more resentful of you / morale drops",
    "両者とも話を聞く姿勢を取り戻す ／ 士気回復": "Both are willing to listen again / morale recovers",
    "両者の士気": "Morale of both",
    "両者を呼び出し、団体のために筋を通させた。火種は残ったが、空気はひとまず収まった。": "You called them both in and made them do right by the promotion. The spark is still there, but the air has settled for now.",
    "両選手の人気": "Popularity of both wrestlers",
    "両選手を選んでください": "Please choose both wrestlers",
    "並び替え:": "Sort:",
    "並び順:": "Order:",
    "中位 → リーダー 因縁": "Mid-tier → leader grudge",
    "中位 → リーダー 絆": "Mid-tier → leader bond",
    "中位メンバー trust": "Mid-tier member trust",
    "中堅": "Mid-card",
    "中堅 — 着実に興行を重ねて": "Mid-tier — keep stacking up shows",
    "中堅上位 — じわじわ登り続けよう": "Upper mid-tier — keep climbing, step by step",
    "中堅級": "Mid-tier",
    "中心にする選手を検索": "Search for a wrestler to center on",
    "中心に設定": "Set as Center",
    "中立": "Neutral",
    "中継": "Broadcast",
    "丸め込み": "Roll-up",
    "主な相手: {names}": "Main opponents: {names}",
    "主力": "Core",
    "主力対決": "Core clash",
    "主力層": "Core tier",
    "主力層 {n}名（大枠含む）": "Core tier: {n} (including the top slot)",
    "主力層: 4〜8番手(最大20点)／控え層: 9〜12番手(最大10点)。<br>満点の基準は業界の主力水準に連動し、業界全体が強くなるほど厳しくなります。<br>怪我人・レンタルは含みません。": "Core tier: 4th–8th (max 20 points) / reserves: 9th–12th (max 10 points).<br>Full marks are pegged to the industry's core standard, so the stronger the business gets, the harsher it becomes.<br>Injured and loaned wrestlers are not counted.",
    "主力級": "Core-tier",
    "乱入者を退けた！": "The intruder was driven off!",
    "亀裂が生まれた": "A crack has opened",
    "了解": "Got it",
    "事務所へ ▶": "To the Office ▶",
    "事務所へ戻る": "Back to the Office",
    "事務運営費": "Office costs",
    "事実": "FACT",
    "二つの派閥が睨み合う状況を、社長は静かに見届けた。": "You watched in silence as the two factions squared off.",
    "二人": "two wrestlers",
    "二人の関係": "The relationship between them",
    "二面": "Page 2",
    "互いに認め合う": "They acknowledge each other",
    "互いを高め合う関係": "A relationship that raises them both",
    "互角": "Even",
    "互角の宿敵": "An evenly matched nemesis",
    "交代": "Replace",
    "交代する枠を選び、代表3名を並べ替える": "Pick a slot to swap and reorder your three representatives",
    "交代する枠を選び、候補棚から選手を選択": "Pick a slot to swap, then choose a wrestler from the shelf",
    "交渉": "Negotiate",
    "交渉から離脱": "Leave Negotiations",
    "交渉する": "Negotiate",
    "交渉の余地なし — {name}は退団を決意しています": "No room to negotiate — {name} has decided to leave",
    "交渉を始める": "Start Negotiating",
    "交渉データがありません": "No negotiation data",
    "交渉プランを選択:": "Choose a negotiating plan:",
    "交渉不成立": "No deal",
    "交渉中": "In negotiation",
    "交渉候補に追加": "Add to Negotiation List",
    "交渉失敗": "Negotiation failed",
    "交渉対象の選手が見つかりませんでした。": "No wrestler to negotiate with was found.",
    "交渉成立": "Deal agreed",
    "交渉成立選手": "Wrestlers signed",
    "交渉期間: 4週間（キャンセル不可）": "Negotiation period: 4 weeks (cannot be cancelled)",
    "交渉終了": "Negotiations Over",
    "交渉開始": "Start Negotiations",
    "交渉開始（{n}名）→": "Start Negotiations ({n}) →",
    "人数": "Headcount",
    "人気": "Popularity",
    "人気 +{n}": "Popularity +{n}",
    "人気 1位": "Popularity — 1st",
    "人気 {n} 到達": "Popularity {n} reached",
    "人気 {pop}": "Popularity {pop}",
    "人気{pop}・集客{draw}": "Popularity {pop} · Draw {draw}",
    "人気が即座にアップします": "Popularity goes up immediately",
    "今はそれどころじゃないと釘を刺す": "Tell her flatly that now is not the time",
    "今はまだ誰も群れていない。生まれる前に禁じておけば、誰の信頼も損なわない": "Nobody has grouped up yet. Ban it before it starts and no one's trust is damaged",
    "今は休ませどき": "Now is the time to rest her",
    "今は声をかけられない": "You can't approach her right now",
    "今は時期じゃない": "Now is not the time",
    "今は約束できない": "You can't promise that right now",
    "今シーズン": "This season",
    "今シーズン累計:": "Season total:",
    "今回のドラフトでは獲得がありませんでした": "You signed no one in this draft",
    "今回の獲得上限（{n}名）に達しています": "You've reached this draft's limit of {n}",
    "今回は固定興行のためカードへ割り込まず、挑戦試合は次の通常興行まで持ち越されます。": "This week's show is locked, so the challenge match won't be slotted in; it carries over to your next regular show.",
    "今回は見送る": "Pass for now",
    "今回は見送る(次は約9か月後)": "Pass for now (the next chance is about nine months away)",
    "今回は辞退する": "Decline this time",
    "今季の収支": "This season's balance",
    "今季を彩った記録": "The records that defined the season",
    "今季防衛 {n}回": "{n} defenses this season",
    "今年のドラフトで": "in this year's draft",
    "今年のドラフトは行われませんでした。": "No draft was held this year.",
    "今年の大会": "This year's tournament",
    "今年の年末も、画面の中は他所の景色だった。": "Another year's end, and what was on the screen was still someone else's world.",
    "今月": "This month",
    "今期、招聘に応じてくれそうなコーチの顔ぶれ。指導タイプと得意スタイルを見て、誰に任せるか決める。": "The coaches likely to accept an offer this term. Look at their coaching type and preferred style, then decide who to trust.",
    "今期、招聘に応じるコーチはいない": "No coach will accept an offer this term",
    "今期の候補にいないコーチです": "That coach is not among this term's candidates",
    "今期はもう秘書に頼んでいます": "You've already asked your secretary this term",
    "今期は依頼済み": "Already requested this term",
    "今期招聘できるコーチがいません": "There are no coaches to bring in this term",
    "今週の行動": "This week's actions",
    "今週はすでに決裁済みです": "You've already approved this week",
    "今週はもう声をかけた": "You've already spoken to her this week",
    "今週はジュニアトーナメント": "The Junior Tournament is this week",
    "今週は季節の特別興行です。通常興行は行えません。": "This week is a seasonal special show. You cannot run a regular show.",
    "今週は季節の特別興行週": "This week is a seasonal special show week",
    "今週は机に並ぶ案件がありません": "Nothing on your desk this week",
    "今週は業界動向の特筆事項なし。<br>業界全体が静かに次の展開を待っている。": "Nothing of note in the business this week.<br>The whole industry is quietly waiting for what comes next.",
    "今週は通常興行を開催できる週ではありません。": "This is not a week when you can run a regular show.",
    "介入": "Intervene",
    "介入しない": "Don't intervene",
    "介入なし。自然減衰に任せる（CD 16週まで再判定なし）": "No intervention. Let it cool off on its own (no new check for 16 weeks)",
    "他 {n}件": "{n} more",
    "他{n}名": "{n} others",
    "他にも続く因縁(全業界)": "Other grudges still burning (industry-wide)",
    "他団体": "Other promotions",
    "他団体との3試合挑戦シリーズ：会場枠内の上位3試合として固定され、カード魅力に専用ボーナスが入ります": "A three-match challenge series against another promotion: locked into the venue's top three slots, with a dedicated bonus to the card's appeal",
    "他団体との競合に敗れました": "You lost out to another promotion",
    "他団体の指名はこのまま進みます。": "The other promotions' picks go ahead as they are.",
    "他枠で選出済み": "Already picked for another slot",
    "代表3名・先鋒 / 中堅 / 大将": "Three representatives · Lead-off / Middle / Captain",
    "代表的な選手": "Notable wrestlers",
    "代表選手": "Representatives",
    "代表選手の編成を確定できませんでした": "Your representative lineup could not be locked in",
    "代表選手を選んでください": "Please choose your representatives",
    "代表選手を選んで対戦": "Choose your representatives and fight",
    "以 後 認 め な い": "NEVER AGAIN",
    "仲 裁": "MEDIATE",
    "仲介して収める": "Step in and settle it",
    "仲裁する（条件未達）": "Mediate (conditions not met)",
    "仲裁監視": "Mediation watch",
    "仲間の絆に小さな亀裂が走った": "A small crack has run through the bond between them",
    "休 暇 週 数": "Weeks Off",
    "休暇の週数が選ばれていません": "You haven't chosen how many weeks off",
    "休暇中の選手には使用できません": "Cannot be used on a wrestler who is on leave",
    "休暇中の選手には約束できない": "You can't promise that to a wrestler on leave",
    "休暇中は興行に欠場します。体調が回復し、蓄積した衰えも少し癒えます。": "She misses shows while on leave. Her condition recovers, and some of the accumulated wear heals.",
    "休養": "Rest",
    "休養中": "Resting",
    "休養重視": "Rest Focus",
    "会場": "Venue",
    "会場の熱": "Venue heat",
    "会場の熱気予測。ここに各試合の注目度(人気・因縁・タイトル・メイン枠など)を掛けた分だけ試合評価に効きます。超満員は試合を熱くし、ガラガラは冷やします。": "Projected heat in the building. Each match's profile (popularity, grudges, titles, main-event status and so on) multiplies into it and lands on the match rating. A packed house makes matches hotter; empty seats cool them down.",
    "会場席数": "Venue capacity",
    "会場費": "Venue cost",
    "会場選択": "Choose a Venue",
    "伸びしろ大": "Lots of room to grow",
    "伸び幅は記録が残っていません": "No record of how much she grew",
    "低下（離脱リスク）": "Falling (risk of departure)",
    "体が重そうです": "Her body looks heavy",
    "体調": "Condition",
    "体調 {n}": "Condition {n}",
    "体調80未満の選手を休養にし、体調80以上で休養方針の選手をバランスに切り替えます。それ以外の方針は維持されます": "Puts wrestlers below 80 condition on rest, and switches those at 80 or above who are resting back to balanced. Every other setting is left alone",
    "体調が大きく戻る。消耗の回復も": "Condition recovers a lot, and some wear with it",
    "体調が少し戻る": "Condition recovers a little",
    "体調が戻り、積み重なった消耗もわずかに癒える": "Condition recovers, and a little of the built-up wear heals",
    "体調・消耗ともに回復は最大。ただし1ヶ月不在": "Maximum recovery for both condition and wear — but she's gone for a month",
    "体調不足": "Condition too low",
    "何もしない": "Do nothing",
    "何もしない。彼女らの自然な決着に任せる": "Do nothing. Let them settle it themselves",
    "何も起きずに流れた": "It passed without anything happening",
    "何を探すかが選ばれていません": "You haven't chosen what to look for",
    "余裕": "Composed",
    "使いどころ": "When to use it",
    "使用楽曲": "Music Used",
    "例: メインセーブ（{n}文字まで）": "e.g. Main save (up to {n} characters)",
    "供給元": "Loaned from",
    "個人ランキング 1位": "Individual rankings — 1st",
    "個人表彰": "Individual Awards",
    "個人集客力が高い選手をメインに": "Puts your biggest individual draws on top",
    "個別の試合データは記録に残っていない。次戦からは時系列で刻まれる。": "There is no match-by-match record yet. From the next match on it will be logged in order.",
    "倒産": "Bankruptcy",
    "倒産する前に黒字経営に持っていこう！ まずは興行を開催して人気を上げ、スポンサー収入（人気20〜）を獲得するのが第一歩。": "Get into the black before you go under! Start by running shows to build popularity and unlock sponsor income (from popularity 20).",
    "倒産までの猶予": "Time before bankruptcy",
    "候 補 者": "The Shortlist",
    "候補": "Candidates",
    "候補 {n}名の調査報告が届きました。<br>ドラフト会場で交渉が始まります。": "Scouting reports on {n} candidates have arrived.<br>Negotiations begin at the draft.",
    "候補6名の中から3名を選び、5名の所属選手でシーズンを開始する": "Choose 3 of the 6 candidates and start the season with a roster of 5",
    "候補: {names}": "Candidates: {names}",
    "候補選手（{a}/{b}名選択済）": "Candidates ({a}/{b} selected)",
    "停止": "Stop",
    "健康": "Healthy",
    "偶数週に対戦カードと会場を決めて興行を開催します。": "On even weeks you set the card and the venue and run a show.",
    "優 勝": "CHAMPION",
    "優勝": "Winner",
    "優勝 {name}。大会結果を記録しました。": "Winner: {name}. The tournament result has been recorded.",
    "優勝{n}回": "{n} tournament wins",
    "優勝決定戦": "Final",
    "優勝発表": "Announcing the winner",
    "優勝賞金": "Prize money",
    "優勢": "Ahead",
    "元": "Former ",
    "元気": "Fresh",
    "元王者#{id}": "Ex-champion #{id}",
    "先取で決着": "First to reach it wins",
    "先鋒": "Lead-off",
    "入れ替わりまで あと{n}週": "{n} weeks until the next rotation",
    "入賞": "Placed",
    "全": "📋",
    "全3試合のシリーズ戦です": "It's a three-match series",
    "全OFF": "All Off",
    "全ON": "All On",
    "全{n}試合": "{n} matches in all",
    "全{n}試合 ─ {a}/{b} 完了": "{n} matches in all ─ {a}/{b} done",
    "全{total}名 / 表示中: {shown}名": "{total} total / showing {shown}",
    "全て": "All",
    "全ての移籍オファーに対応しました。": "You've responded to every transfer offer.",
    "全スタイル": "All styles",
    "全リンク": "All Links",
    "全体": "Overall",
    "全体に戻る": "Back to Overall",
    "全体を表示": "Show All",
    "全候補の確認が完了しました": "You've reviewed every candidate",
    "全受賞者一覧": "All Award Winners",
    "全受賞者発表": "Announcing All Winners",
    "全員が入るように表示": "Fit everyone in view",
    "全団体": "All promotions",
    "全団体ロースター": "All Promotion Rosters",
    "全団体戦終了": "All interpromotional matches complete",
    "全国女子プロレス最強王者決定戦": "Crowning the Strongest in Women's Wrestling",
    "全国生中継": "Live nationwide",
    "全国統一王者": "Unified National Champion",
    "全景": "Wide",
    "全期間": "All time",
    "全枠解放済み": "All slots unlocked",
    "全治 {n}週間": "Out for {n} weeks",
    "全治{n}週": "Out {n} weeks",
    "全試合スキップ": "Skip All Matches",
    "公式戦化": "Made official",
    "内-/外+": "in-/out+",
    "内紛フラグ点灯": "Infighting flag lit",
    "再 燃": "REIGNITED",
    "再生中": "Playing",
    "再試行失敗: ": "Retry failed: ",
    "冷": "Cold",
    "冷え切っている": "Gone cold",
    "冷めぬ確執の記録": "A record of grudges that won't cool",
    "冷戦": "Cold war",
    "処 置": "Treatment",
    "処置が選ばれていません": "You haven't chosen a treatment",
    "出 入 り": "Ins and Outs",
    "出場{n}回": "{n} appearances",
    "出場なし": "No appearances",
    "出場可能な選手が不足しており、対戦カードを組めませんでした": "There were not enough available wrestlers to put a card together",
    "出場可能選手": "Available wrestlers",
    "出場報酬: {v}万円": "Appearance fee: ¥{v}0k",
    "出場枠:": "Entry slots:",
    "出場枠ごとに2名を選出してください。同じ選手は複数チームに登録できません。未編成枠は締切時におまかせ編成されます。": "Choose two wrestlers for each entry slot. The same wrestler cannot be on two teams. Empty slots are filled automatically at the deadline.",
    "出場資格のある選手": "Eligible wrestlers",
    "出場選手を選択（残り{n}枠）": "Choose your entrants ({n} slots left)",
    "出演料等": "Appearance fees, etc.",
    "分裂": "Split",
    "分裂回避（破裂に至らず）": "Split avoided (it didn't rupture)",
    "分類": "Type",
    "切磋琢磨の果てに、序列が動いた": "They pushed each other, and the pecking order moved",
    "初代 全国統一王者": "First Unified National Champion",
    "初代王者": "First champion",
    "初代王者決定戦": "Match to crown the first champion",
    "初戦の相手": "First-round opponent",
    "初登場": "New entry",
    "初顔合わせ": "First meeting",
    "別カードに置換": "Replace with another match",
    "削除": "Delete",
    "前の号 ▶": "Previous issue ▶",
    "前シーズン比:": "vs last season:",
    "前フォール:": "Previous fall:",
    "前リーダー": "Former leader",
    "前・団体王者": "Former promotion champion",
    "前年 {rank}位": "#{rank} last year",
    "前章 / {title}": "Previous chapter / {title}",
    "前章なし": "No previous chapter",
    "前週 {n}位": "#{n} last week",
    "前週 {n}位 から上昇": "Up from #{n} last week",
    "前週 {n}位 から下降": "Down from #{n} last week",
    "副将": "Deputy",
    "加入": "Joined",
    "加入予定選手": "Wrestlers set to join",
    "劣勢": "Behind",
    "効果": "Effect",
    "勃 発": "OUTBREAK",
    "動員×{mult}": "Attendance ×{mult}",
    "勝 利": "VICTORY",
    "勝<strong>{n}</strong>": "W <strong>{n}</strong>",
    "勝ち上がり": "Advancing",
    "勝ち上がるほど上へ": "Win and you move up",
    "勝ち上がるほど上へ / 消耗は次の試合へ持ち越し": "Win and you move up / wear carries into the next match",
    "勝ち残り": "Survivor",
    "勝ち残り対抗戦 優勝": "Survivor Interpromotional Match — Winner",
    "勝ち点": "Points",
    "勝ち筋:": "Path to victory:",
    "勝ち越しボーナス +15PT": "Winning-record bonus +15PT",
    "勝ち越し中": "Winning record",
    "勝ち越し派閥": "Faction with the winning record",
    "勝利": "Win",
    "勝利団体": "Winning promotion",
    "勝点 +1": "Points +1",
    "勝率": "Win rate",
    "勝率{rate}%": "Win rate {rate}%",
    "勝者": "Winner",
    "勝者↑↑ ／ 敗者↓": "Winner ↑↑ / loser ↓",
    "勝者はリングに残り、敗者側の次の選手が登場": "The winner stays in the ring and the losing side sends out its next wrestler",
    "勝者コンディション": "Winner's condition",
    "勝者リーダー trust": "Winning leader's trust",
    "勝者勝点": "Winner's points",
    "勝者派閥": "Winning faction",
    "勢い": "Momentum",
    "勢い:{v}": "Momentum: {v}",
    "勢力図": "Balance of Power",
    "単独指名 — 競合なし": "Sole bid — no competition",
    "原石": "Diamond in the rough",
    "厳しく改定": "Revise it hard",
    "参加する選手を選んでください。": "Please choose the wrestlers taking part.",
    "参加者 {n}名": "{n} taking part",
    "友": "Ally",
    "友好的な関係": "A friendly relationship",
    "友情と闘志": "Friendship and fight",
    "友情と闘志、矛盾しない関係": "Friendship and fight, with no contradiction",
    "友情・親愛": "Friendship · affection",
    "反撃のタッチ！": "The tag for the comeback!",
    "収入": "Income",
    "収入{a}万 / 支出{b}万": "Income ¥{a}0k / expenses ¥{b}0k",
    "収入の柱はチケット・グッズ・スポンサー・放映料。支出の柱は給与です。選手が育って格が上がれば、給与も上がります。赤字が続けば資金危機に（→ ゲームの目的）。": "Your income rests on tickets, merch, sponsors and broadcast fees. Your outgoings rest on salaries. As wrestlers grow and rise in stature, their pay rises with them. Keep running a deficit and you head for a cash crisis (→ the point of the game).",
    "収支": "Balance",
    "取材、誰に委ねますか？": "Who takes the interview?",
    "取材は断った。{name}は表に出ず、しばらく沈む。": "You turned the interview down. {name} stays out of sight and goes quiet for a while.",
    "取材は無難に終わった。": "The interview ended without incident.",
    "取材を断る": "Turn down the interview",
    "取材オファーが届いた。誰がどう答えるかで、誌面の色が変わる。": "An interview request has come in. Who answers, and how, decides the color of the page.",
    "受けた代表・決着つかず": "Representative who answered · no decision",
    "受けて、勝った代表": "The representative who answered and won",
    "受けて、敗れた代表": "The representative who answered and lost",
    "受けて立ち、団体を勝たせた代表": "The representative who stood up and won it for the promotion",
    "受けて立った代表": "The representative who stood up",
    "受けて立つ": "Stand up to it",
    "受ける": "Accept",
    "受け入れる": "Accept",
    "古参選手": "Long-serving wrestler",
    "召集通知": "Call-up notice",
    "台多数": " and more in that range",
    "右チーム": "Right team",
    "号外": "EXTRA",
    "各カード下部のゲージ＝粘り度（右に行くほど限界に近い）": "The gauge under each card = staying power (the further right, the closer to the limit)",
    "各団体の関心は事前情報。実際の交渉では予測と異なる動きを見せることもある。": "Each promotion's interest is advance intel. In the actual negotiations they may move differently than predicted.",
    "合同企画": "Joint project",
    "合同企画を承認": "Approve the joint project",
    "合宿、取材、同門対決、下剋上——派閥がらみの報せには、社長の判断を求めるものもあります。静観するか、油を注ぐか、水を差すか。": "Training camps, interviews, stablemate clashes, coups — some faction news needs your call. Watch it play out, pour oil on it, or throw water on it.",
    "合宿の手応えが出てきた（{n}名）": "The training camp is starting to show ({n})",
    "合宿の手応えで{name}の気持ちが前向きになってきた": "The training camp is working, and {name} is coming round",
    "合計": "Total",
    "合計 {n}pt": "Total {n}pt",
    "同じ志、別の道": "Same conviction, different roads",
    "同じ派閥に所属": "In the same faction",
    "同じ週に敵地遠征があるため、受けた挑戦試合は破棄せず次の通常興行まで持ち越します。": "You have an away trip that same week, so the challenge match you accepted isn't dropped — it carries over to your next regular show.",
    "同士討ち！": "Friendly fire!",
    "同期なし(単独エース)": "No peers from her year (a lone ace)",
    "同盟締結": "Alliance formed",
    "同行する2名を選ぶ": "Choose the two who go with her",
    "同行できる選手がいません": "No one is available to go along",
    "同行者 {n}": "Companion {n}",
    "同門・派閥": "Stable · faction",
    "名前": "Name",
    "名前で検索": "Search by name",
    "名前順": "By Name",
    "周囲の数名が自然と集まっているようです。": "A few of the others seem to be drifting together.",
    "和 　 解": "RECONCILED",
    "和解": "Reconciliation",
    "喧嘩": "Quarrel",
    "四人": "four wrestlers",
    "回復中": "Recovering",
    "回復後HP": "HP after recovery",
    "回復期間半減・手厚い対応が伝わる": "Recovery time halved, and she feels well looked after",
    "因 縁 の 一 戦": "THE GRUDGE MATCH",
    "因 縁 勃 発": "A GRUDGE IS BORN",
    "因 縁 決 着": "GRUDGE SETTLED",
    "因縁": "Grudge",
    "因縁 {a} / 相手との関係 {b}": "Grudge {a} / relationship {b}",
    "因縁 激発展({loser} → {winner})": "Grudge escalates sharply ({loser} → {winner})",
    "因縁を刻まれた": "A grudge has been carved in",
    "因縁・ライバル": "Grudges · rivals",
    "因縁・鮮度・話題性を考慮した最適カード": "The best card, weighing grudges, freshness and buzz",
    "因縁列伝": "Chronicle of Grudges",
    "因縁対決": "Grudge match",
    "団体": "Promotion",
    "団体として": "As a promotion",
    "団体と所属選手の時間": "The promotion and its wrestlers over time",
    "団体の名声が業界に轟いた！\n": "Your promotion's name has rung out across the business!\n",
    "団体の格が上がった。": "Your promotion has risen in stature.",
    "団体の知名度が足りません({n} 必要)": "Your promotion's renown is too low ({n} needed)",
    "団体の知名度が足りません！": "Your promotion's renown is too low!",
    "団体の足跡": "The promotion's footsteps",
    "団体を選んでください": "Please choose a promotion",
    "団体スコア": "Promotion score",
    "団体スコア {a}–{b}": "Promotion score {a}–{b}",
    "団体プロフィール": "Promotion Profile",
    "団体ランキングと来季": "Promotion Rankings and Next Season",
    "団体人気": "Promotion popularity",
    "団体人気40まで補助金支給": "Grant paid until promotion popularity 40",
    "団体人気:": "Promotion popularity:",
    "団体人気{pop}以上で交渉可能": "Negotiable at promotion popularity {pop} or above",
    "団体人気が25を突破！ 団体規模の拡大で契約枠に余裕ができました。": "Promotion popularity has passed 25! As the promotion grows, you have more room in your contract slots.",
    "団体人気が50を突破！ 主力と若手をより厚く抱えられるようになりました。": "Promotion popularity has passed 50! You can now carry more depth in both your core and your young wrestlers.",
    "団体人気が70を突破！ メジャー団体の規模にふさわしい契約枠が確保されました。": "Promotion popularity has passed 70! You now have the contract allowance of a major promotion.",
    "団体人気の歩み — 旗揚げから": "Promotion popularity over time — since day one",
    "団体人気をそのまま0〜100で点数化": "Scores promotion popularity directly, 0 to 100",
    "団体人気推移": "Promotion popularity trend",
    "団体全体の空気は、成長やイベントの起きやすさに響きます。勝ちが続けば和み、連敗と空席が続けば荒みます。「人望」のある選手は、いるだけで空気を少し明るくします。": "The mood of the whole promotion feeds into growth and into how often events fire. A run of wins settles it; losing streaks and empty seats sour it. A wrestler others look up to lifts the mood just by being there.",
    "団体全員": "The whole promotion",
    "団体全員 ({n}名)": "The whole promotion ({n})",
    "団体名を入力": "Enter your promotion's name",
    "団体年代記": "Promotion Chronicle",
    "団体戦の発起人": "Who called for the interpromotional match",
    "団体戦挑戦の直訴": "Direct appeal for an interpromotional match",
    "団体戦決着": "Interpromotional match settled",
    "団体枠 — {n}名を選出(団体順位による)": "Promotion slots — choose {n} (based on your ranking)",
    "団体格ベース（自団体0 / S級+50 / A級+30 / B級+15）<br>＋ 殿堂入り盾（★殿堂+8 / ★★ゴールド+10 / ★★★レジェンド+13）<br>＋ 対抗戦通算勝利数 ÷ 5": "Based on promotion class (your own 0 / Class S +50 / Class A +30 / Class B +15)<br>+ Hall of Fame shields (★ Hall of Fame +8 / ★★ Gold +10 / ★★★ Legend +13)<br>+ total interpromotional wins ÷ 5",
    "団体比較": "Promotion Comparison",
    "団体王者 · 防衛成功": "Promotion champion · successful defense",
    "団体評価↓ ／ 関係悪化": "Promotion standing ↓ / relationship worsens",
    "固定収入": "Fixed income",
    "固有特性": "Unique trait",
    "固有特性なし": "No unique trait",
    "在位 {n}年": "{n} years as champion",
    "在位中": "Current reign",
    "在位期間": "Length of reign",
    "在籍選手": "Wrestlers on the roster",
    "均等": "Even",
    "埋まらぬ亀裂の裏側": "Behind a crack that won't close",
    "基礎力": "Base strength",
    "基礎力 — 今そこにある戦力": "Base strength — the power you have right now",
    "基礎力 ＋ レガシー ＋ 対戦PT ＋ 実績 の合計。<br>このポイントで業界順位が決まる。": "Base strength + legacy + match PT + achievements, added together.<br>These points decide your place in the industry rankings.",
    "報告として、お耳に入れておきます。": "I'll put this in front of you as a report.",
    "声かけ": "Talk to her",
    "声をかける状況ではない": "This isn't the moment to talk to her",
    "変化なし": "No change",
    "変更": "Change",
    "夏季ジュニア ・ {name} {result}": "Summer Junior · {name} {result}",
    "外部コーチ": "Guest coach",
    "外部コーチの招聘期間中は担当コーチを変更できません（終了後に自動で元へ戻ります）": "You cannot change assigned coaches while a guest coach is on site (it reverts automatically when they leave)",
    "外部コーチの指導が実を結び始めた（{n}名）": "The guest coach's work is starting to bear fruit ({n})",
    "外部コーチの指導で{name}の気持ちが前向きになってきた": "Under the guest coach, {name} is coming round",
    "大きな変化は数値には出なかったが、確かな手応えが残った": "Nothing much showed in the numbers, but something real came out of it",
    "大ニュース・タッグ歴代最高評価": "Big news · best tag match rating ever",
    "大会MVP": "Tournament MVP",
    "大会MVP発表へ": "To the Tournament MVP",
    "大会が生んだ関係": "Relationships the tournament created",
    "大会の進行データを保持しています。大会画面に戻って進行を続けてください。": "The tournament is still in progress. Go back to the tournament screen to continue.",
    "大会へ戻る": "Back to the Tournament",
    "大会を終える": "End the Tournament",
    "大会ベストバウト": "Tournament Best Bout",
    "大会最高評価": "Highest rating of the tournament",
    "大会結果": "Tournament Results",
    "大会結果へ": "To the Tournament Results",
    "大会規定": "Tournament rules",
    "大試合": "Big match",
    "失敗しました": "It failed",
    "失敗時損失": "Loss if it fails",
    "契約が成立しました": "The contract is signed",
    "契約する": "Sign",
    "契約不可": "Cannot sign",
    "契約交渉（{a}/{b}）": "Contract talks ({a}/{b})",
    "契約基準": "Contract terms",
    "契約更新 完了": "Contract renewals complete",
    "契約枠拡大！": "More contract slots!",
    "契約金": "Signing fee",
    "契約金 (万)": "Signing fee (×10k)",
    "契約金:": "Signing fee:",
    "契約金: ¥{n}万": "Signing fee: ¥{n}0k",
    "契約金合計": "Total signing fees",
    "奪取{wins}+防衛{defenses}{holding}": "{wins} won + {defenses} defended{holding}",
    "女子プロレス団体経営シミュレーション": "A women's pro wrestling management simulation",
    "好 敵 手 誕 生": "A WORTHY RIVAL",
    "好敵手 — 絆・因縁 ともに上昇(相互)": "Worthy rivals — bond and grudge both rise (mutual)",
    "始動": "Begins",
    "季": "📅",
    "季節の特別興行": "Seasonal special show",
    "安い順": "Cheapest First",
    "安全": "Safe",
    "安定": "Stable",
    "完了": "Done",
    "定期興行": "Regular shows",
    "実力が序列を書き換えた": "Ability rewrote the pecking order",
    "実力主義": "Meritocracy",
    "実力副官": "Backbone",
    "実施": "Carried out"
  }
  );
})();
